### ISSUE TITLE
Revert to version where MySQL also works on iOS

### ISSUE THREAD

**Issue by JeroenBoersma** [JeroenBoersma/docker-compose-development#1]
Due permission differences between iOS and Ubuntu you cannot start the database container on iOS.

This was possible before by creating a data container for db first, will revert to that

**Comment by Caroga** [comment]
I don't know if you wanna fully revert back to the data container you already had or want to implement it differently, just wanted to leave this reference to the data container I use, which has a footprint of 125 bytes. 
https://hub.docker.com/r/tianon/true/

P.s.: 
I've used this in the following setup, in a repository I've setup to help a friend learn and understand the basics of Docker.
https://github.com/Caroga/docker-development/blob/master/data/dockerfiles/data/Dockerfile

**Comment by JeroenBoersma** [comment]
fixed as of today... description in the readme
