### ISSUE TITLE
Upgrade PHP 7.2 to 7.2.19

### ISSUE THREAD

**Issue by peterjaap** [JeroenBoersma/docker-compose-development#100]
We're now at 7.2.18, which contains libsodium 1.0.11 but for Magento 2.3.2 we need libsodium minimum version 1.0.13. PHP 7.2.19 contains libsodium 1.0.17.

See https://support.hypernode.com/changelog/release-6364-magento-2-preinstall-updated-to-2-3-2/

**Comment by JeroenBoersma** [comment]
We use base image `php:7.2` from docker which is shipped with `libsodium 1.0.11` also in `PHP 7.2.19`

So, we need to manually install `libsodium 1.0.17` from a source

**Comment by JeroenBoersma** [comment]
related information for others looking for this

Libsodium installation: https://download.libsodium.org/doc/installation
Pecl https://pecl.php.net/package/libsodium

**Comment by JeroenBoersma** [comment]
Helpful resource: https://github.com/jreckner/docker-libsodium/blob/master/Dockerfile

**Comment by JeroenBoersma** [comment]
currently building with latest libsodium!

**Comment by JeroenBoersma** [comment]
https://hub.docker.com/r/srcoder/development-php/builds

**Comment by JeroenBoersma** [comment]
done!

For most if not all (if path commands are added)
```
cdw
cd ..
git pull --autostash
dev rebuild
```
