### ISSUE TITLE
Can't run Varnish with Magento 2

### ISSUE THREAD

**Issue by marciomaciel** [JeroenBoersma/docker-compose-development#102]
## I'm trying to run Magento with Varnish, but I got this error:
> Error 503 Backend fetch failed
Backend fetch failed
> Guru Meditation:
> XID: 3
> Varnish cache server

## Steps to reproduce:
1. Install Magento 2 (In my case I'm using Magento 2.3.2)
2. Execute the Magento command-line to generate vcl config: bin/magento varnish:vcl:generate > varnish.vcl
3. Move the generated file varnish.vcl to conf/varnish.vcl
4. Edit the conf/varnish.vcl and change .host value from localhost to web and .port to 80
5. Run dev rebuild

Anyone can help me? Thank you!

**Comment by JeroenBoersma** [comment]
Of coarse we can help you out!

By default, Magento VCL export connects to `localhost`, this is wrong :) in our case.
We have different containers for web and varnish.

We need to explicitly set the backend host/port.

Also, the Magento `vcl:generate` adds a probe without a hostname and therefore it cannot do a health_check to the backend, `dev varnish-vcl-import {VARNISHFILE}` removes this .probe.

This works!

```
bin/magento varnish:vcl:generate --backend-host=web --backend-port=80 > varnish.vcl
# added lately and updated today to remove the probe
dev varnish-vcl-import varnish.vcl

# I've added disable too
dev varnish-vcl-disable
# renames file from varnish.vcl -> varnish.vcl.off

```
