### ISSUE TITLE
Add Symfony 4

### ISSUE THREAD

**Issue by RenanLazarotto** [JeroenBoersma/docker-compose-development#104]
The current Symfony configuration files are intended for Symfony 2/3 and doesn't works for Symfony 4 based applications. Adding 'symfony' in any SF4-based application makes it stop working (404, even on project root).

Here are the recommended Nginx  config for SF4: https://symfony.com/doc/current/setup/web_server_configuration.html#nginx

I've tried manually but my Nginx knowledge is too limited to understand what I'm trying to achieve :grin:

**Comment by JeroenBoersma** [comment]
Let's check

**Comment by JeroenBoersma** [comment]
I see, so they changed from `app.php` to `index.php`
So if you use anything else than `*.symfony.extension` the default settings should be sufficient.

for instance:

`workspace/my/project/` with the symfony installation it should work as expected when openinng: `my.project.{extension}`

**Comment by RenanLazarotto** [comment]
> So if you use anything else than *.symfony.extension the default settings should be sufficient.
Been doing this for the past few days. As long as I can remember, I had no trouble.
If the default settings should be sufficient in your words, then I see no reason to mess with something that isn't broken. I just pointed out because I know pretty much nothing about nginx, so I wouldn't know if something needed to be changed :D
