### ISSUE TITLE
Unable to cancel/kill commands when executed via dev php

### ISSUE THREAD

**Issue by rickkuilman** [JeroenBoersma/docker-compose-development#107]
Commands executed through the `php` command are not killable with `ctrl + c` when the command is being executed. 

When executed via `dev console`, it is possible to kill the command.

**Comment by JeroenBoersma** [comment]
Thanks for bringing this up... the problem is because the `docker-php-entrypoint.sh` doesn't catch the kill command when running subcommands...
Most likely because it's normaly used to run fpm... I can try some stuff, but feel free to blend in...

I didn't came up with a solution (yet)

**Comment by JeroenBoersma** [comment]
It's in the way commands are started in a sub-env via docker.
There is a work around with `trap`

Just add `trap` before the original command to make ctrl-c work.
`dev php -R "<?php sleep(3);"` -> `dev trap php -R "<?php sleep(3);"`

To detach from running containers and killing them, `ctrl-p`, `ctrl-q` does the trick.. TIL
