### ISSUE TITLE
Add Redis Web UI

### ISSUE THREAD

**Issue by rickkuilman** [JeroenBoersma/docker-compose-development#108]
It's easier to manage redis via some kind of web GUI. It would be handy if it's included by default in the package.

**Comment by JeroenBoersma** [comment]
Hi Rick, any suggestions on a native image for that on docker hub?
didn't ran into any trouble using the commandline yet, but happy to add a cool feature...

Other tips: Perhaps there is a PHP package for that... If so it'll be easy as creating a directory in `workspace` and for example `services/redis/public` extracting here, point to `redis` as host and voila... in your browser `services.redis.localhost`

**Comment by peterjaap** [comment]
I use https://github.com/erikdubbelboer/phpRedisAdmin for that.

Get the IP of the redis docker container with docker inspect and run;

`docker run --rm -it -e REDIS_1_HOST=172.17.0.2 -e REDIS_1_NAME=MyRedis -p 8001:80 erikdubbelboer/phpredisadmin`

Then open http://localhost:8001

**Comment by JeroenBoersma** [comment]
> I use https://github.com/erikdubbelboer/phpRedisAdmin for that.
> 
> Get the IP of the redis docker container with docker inspect and run;
> 
> `docker run --rm -it -e REDIS_1_HOST=172.17.0.2 -e REDIS_1_NAME=MyRedis -p 8001:80 erikdubbelboer/phpredisadmin`
> 
> Then open http://localhost:8001

docker-custom.yml
```YAML
version: "3"

services:
  redisweb:
    image: erikdubbelboer/phpredisadmin
    ports:
      - 127.0.0.1:8001:80
    links:
      - redis

```

```bash
dev down && dev up
```

Now it's persistent...



```
