### ISSUE TITLE
Magento 2 : unable to purge the Varnish cache when flushing the admin cache

### ISSUE THREAD

**Issue by julienloizelet** [JeroenBoersma/docker-compose-development#113]
I guess this is not a real issue but instead some Varnish configuration misspelling.

In order to work with Magento and Varnish, I created a `varnish.vcl` file in the `conf` folder.

Launching the `dev up` command works as expected : a varnish container is well created.

I can see the `x-magento-cache-debug` header, so I think varnish is working.

But when I flush the cache from the Magento admin, I think that something goes wrong with the Varnish purge.

For example, if I access to the page : `m23.magento2.localhost/default/gear/fitness-equipment.html` two times I see  `x-magento-cache-debug:HIT` meaning that this page was well cached.

But if I flush the Magento cache, it is still `HIT` when I reload this page.

If I enter in the container varnish and ban the url :

     sudo docker exec -it magento2_varnish_1 sh
     varnishadm
     ban req.http.host == m23.magento2.localhost && req.url == /default/gear/fitness-equipment.html

and then reloading the page : it gives me a `x-magento-cache-debug:MISS` as expected.

I guess that there is something wrong with my varnish.vcl acl purge part. At this moment, I tried different things like :

     acl purge {
    "172.17.0.13";
    "localhost";
    "127.0.0.1";
    "web";
    }

but all my tests have failed ... Do you have an idea of what should be in this part ?

**Comment by JeroenBoersma** [comment]
there are a few problems with this:

- Magento adds a probe to localhost, without a hostname, which will be removed with `varnish-vcl-import`
- There is no `direct` link from the php server to the webserver which makes purges from the admin a little difficult

To flush easily from commandline: to clear everything

```bash
dev varnishadm ban "req.url ~ /"
```

You can also run
```bash
dev exec varnish varnishhist
dev exec varnish varnishlog
```

**Comment by julienloizelet** [comment]
Thanks @JeroenBoersma ,

with the help of your comment, I finally succeed (but this is for the moment not user friendly at all..). 

So, for those who may be interested in, here is what I did :

> There is no direct link from the php server to the webserver which makes purges from the admin a little difficult

In order to have such a link : 
- I had first to get the IP of the `ssl` container (a request to the `ssl` container will arrive to the `varnish` container by some proxy magical).
This `SSL_IP`  is the result of 

      sudo docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' magento2_ssl_1

In my case, `SSL_IP = 172.17.0.14`

- Then, I put this `SSL_IP` in the `acl purge` part of my `varnisch.vcl` file :

      vcl 4.0;
      import std;
      backend default {
        .host = "web";
        .port = "80";
        .first_byte_timeout = 600s;
      }
      acl purge {
       "172.17.0.14";
      }

- Finally, I had to change some configuration in Magento 2 : 

      dev php bin/magento setup:config:set --http-cache-hosts=172.17.0.14:80

With that, a flush in admin implies a purge in varnish.

Hope this will help.
