### ISSUE TITLE
Moving MySQL existing volume 

### ISSUE THREAD

**Issue by RenanLazarotto** [JeroenBoersma/docker-compose-development#114]
Hey there!

I see that it is possible to specify where you want your databases to be (as stated in the readme), but it assumes that they where already somewhere else rather than the default place.

The problem is that I need to move my databases from the default location to somewhere else and I can't figure it out. What do I need to do? Or just by pointing it, like in the readme, will move it for me?

**Comment by peterjaap** [comment]
It's possible to move, here's some more info; https://github.com/JeroenBoersma/docker-compose-development/issues/67#issuecomment-343079517

**Comment by RenanLazarotto** [comment]
> It's possible to move, here's some more info; [#67 (comment)](https://github.com/JeroenBoersma/docker-compose-development/issues/67#issuecomment-343079517)

Interesting, thanks! it would be nice if this could be set at setup time (for example, it would be nice if the setup command asked where I wanted to place my workspace directory), but for the time being, this will do.
