### ISSUE TITLE
Php  version on OSX

### ISSUE THREAD

**Issue by Martinsl** [JeroenBoersma/docker-compose-development#115]
To change the php version in Linux we just have to create the .php file (e.g. .php72), I tried creating it on osx, but it wasn't working.
While debugging the issue I found that the sed is not working correctly:
If i run the sed in Linux it returns the php versions, one in each line, but in osx it returns:
<img width="750" alt="image" src="https://user-images.githubusercontent.com/7865621/68877345-a93ed980-06e4-11ea-90d4-e50967b71549.png">

I changed the sed regex and now it is working as expected:
<img width="750" alt="image" src="https://user-images.githubusercontent.com/7865621/68877389-bfe53080-06e4-11ea-833f-45400a4550ce.png">

I'm opening this issue so that we can find the best way to check this differences between osx and linux (and if you want to add them to this project)

**Comment by Martinsl** [comment]
So, I created a fork and added a few modifications (WIP, just making it work asap) to make it work on osx:
https://github.com/Martinsl/docker-compose-development/tree/feature/osx

Basically I had to make it stop asking for sudo, added the sed modifications, removed the workspace volume mount after the setup and fixed the docker-sync.yml file.
Also, in the php.ini I changed the remote host to:
`xdebug.remote_host = host.docker.internal`

**Comment by JeroenBoersma** [comment]
> Edit:
> Also, changed the port 80 to the web container after I started using docker-sync.
> It was working ok before (but VERY slow), but after I started using docker-sync I couldn't make nginx work anymore. After I moved the port 80 to the web container, magento2 started working again

Strange, doesn't ring a bell with me, not on OSX..


====

Fixed the sed with your tip, so resolved.

The remote host can also be resolved, I will add and `extra_hosts` section only on Linux with the remote machine `172.17.0.1:host.docker.internal` and this way it will work for OSX and Linux with the same settings.
