### ISSUE TITLE
Elasticsearch wrong version

### ISSUE THREAD

**Issue by peterjaap** [JeroenBoersma/docker-compose-development#116]
Elasticsearch docker compose file contains version 7.1.1 while Magento's requirement is 6.1.1

https://github.com/JeroenBoersma/docker-compose-development/blob/master/build/dist/docker-compose-elasticsearch.yml#L5

https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/es-overview.html#es-spt-versions

**Comment by WouterSteen** [comment]
6.1.1 is not available anymore, so you have to use `6.5.4`
