### ISSUE TITLE
wsl fresh install - php doesnt work

### ISSUE THREAD

**Issue by syffs** [JeroenBoersma/docker-compose-development#117]
everything works very well, except PHP. I can reach http://test.project.localhost/index, but http://test.project.localhost/info returns a 404:
![image](https://user-images.githubusercontent.com/4192037/70723037-8cec8780-1cf8-11ea-92dc-aa5b065afea4.png)

I've tried changing php version, but no improvement.

here's my workspace:
![image](https://user-images.githubusercontent.com/4192037/70724206-75160300-1cfa-11ea-9f71-803495c8c6bd.png)

any idea how I can debug this ?

**Comment by syffs** [comment]
ok my bad: the ".php" extension seems to matter in the url.

http://test.project.localhost/info.php does return a phpinfo

**Comment by JeroenBoersma** [comment]
thanks for the question, happy you resolved it :)
