### ISSUE TITLE
magento2 deployment - cannot reach setup page

### ISSUE THREAD

**Issue by syffs** [JeroenBoersma/docker-compose-development#118]
I'm running this under WSL, everything seems to work properly (I can reach http://test.project.localhost/info.php and see phpinfo) except magento.

here are the steps, I went through:
1. download [magento2-2.3.3 with sample data](http://pubfiles.nexcess.net/magento/ce-packages/magento2-with-samples-2.3.3.tar.gz)
2. extract to `workspace/project/mage`, here is how it looks:
![image](https://user-images.githubusercontent.com/4192037/70749977-c8557900-1d2d-11ea-92d5-84b3b59286d7.png)
3. trying to reach setup page:
    - http://project.mage.localhost - ends up on http://project.mage.localhost/setup with fatal error `Too many redirects`
    - http://project.mage.magento2.localhost - ends up on http://project.mage.magento2.localhost/setup/ with 404
![image](https://user-images.githubusercontent.com/4192037/70750243-56316400-1d2e-11ea-997e-897d80eff0b5.png)

did i miss anything ?

**Comment by peterjaap** [comment]
Use 'magento2' instead of 'mage2' and you should see the site at http://project.magento2.localhost

**Comment by syffs** [comment]
Thanks for the quick reply ! I did that:
![image](https://user-images.githubusercontent.com/4192037/70751180-2c793c80-1d30-11ea-9857-c9df1a1c4dbf.png)
http://project.magento2.localhost is redirected to http://project.magento2.localhost/setup/ but still ends up with 404

**Comment by JeroenBoersma** [comment]
Yeah, because we favor `commandline` / `composer` installations.

Open up a console in PHPStorm
```bash
bin/magento setup:install
```
https://devdocs.magento.com/guides/v2.3/install-gde/composer.html#command-line

**Comment by JeroenBoersma** [comment]
I checked, we have the nginx reference, let met check this out... Please hold the line :)

**Comment by syffs** [comment]
> Please hold the line :)

sure thanks for the help !

> Open up a console in PHPStorm
> 
> ```shell
> bin/magento setup:install
> ```

Indeed I managed to get a working magento through CLI install. I guess there's something blocking the web install in nginx config (I'm not an nginx expert tho).

Just to be sure, when you say "open a console", you mean `dev console`, and then `bin/magento setup:install`, because the installer does need direct access to the DB ?

**Comment by JeroenBoersma** [comment]
Yes yes yes... I found the underlaying problem... Which was in the Nginx configuration.

In the Magento 2 configuration I forward to the `@php` location.
Location directive in nginx inherits the server root and not the location root set in another location section.

I added a variable to forward the docroot explicitly. From now on anyone with Magento 2 can use the `/setup` path for Magento 2.

**Comment by JeroenBoersma** [comment]
> Just to be sure, when you say "open a console", you mean dev console, and then bin/magento setup:install, because the installer does need direct access to the DB ?

yes `dev console`. In `dev console` the `db` is also available.

**Comment by JeroenBoersma** [comment]
Also `/update` directive works correctly now... All resolved then ;)

**Comment by JeroenBoersma** [comment]
I anything, don't hesitate!

**Comment by syffs** [comment]
Thanks a lot, it all works now ! Magento browsing is sometimes ok and sometimes insanely slow, any suggestion to speed it up ?

**Comment by JeroenBoersma** [comment]
Yes, this is because of developer mode... This means it'll try to create the files on the fly....

You could run a
```bash
# Generate static files for en_US(choose any other if you have a other locale, or define 2 or more)
bin/magento set:sta:dep -fa admin en_US
# Generate static files for frontend
bin/magento set:sta:dep -f -t Magento/Blank en_US nl_NL de_DE
```
Doing so will really speed up the first time load...

Also take a look at [cache-clean.js](https://github.com/JeroenBoersma/docker-compose-development/issues/92#issuecomment-497736981) implementation.
