### ISSUE TITLE
Install composer

### ISSUE THREAD

**Issue by JeroenBoersma** [JeroenBoersma/docker-compose-development#12]
Add composer in the php containers so you do not have to install them yourself

**Comment by JeroenBoersma** [comment]
https://github.com/JeroenBoersma/docker-compose-development/commit/088ffbbf09c207968df3edc90b50eb0cf0988279

**Comment by JeroenBoersma** [comment]
I had a wait whut moment after seeing this

https://github.com/composer/docker

Will take a serious look at that

**Comment by Caroga** [comment]
Maybe take a look at the official implementation as well ? This is what I currently use in my dev env. 
https://hub.docker.com/r/composer/composer/
https://github.com/RobLoach/docker-composer  <- corresponding github repo

**Comment by JeroenBoersma** [comment]
@Caroga consider this done... Fixed this this morning

https://github.com/JeroenBoersma/docker-compose-development/commit/040c2345c2773a700c4535808fdce34233d3bf5f
