### ISSUE TITLE
Add mage2gen command line tool

### ISSUE THREAD

**Issue by peterjaap** [JeroenBoersma/docker-compose-development#122]
https://mage2gen.com/commandline/

**Comment by JeroenBoersma** [comment]
I already take a dive into that... let me see where it wen't

**Comment by JeroenBoersma** [comment]
Ah, this is how I did this, without the need of native support...

# new file in `workspace/bin/mage2gen`
```sh
#!/bin/sh

export PYTHONPATH=/data/.applications/mage2gen;
python3 /data/.applications/mage2gen/bin/mage2gen "$@"
return $?;
```

in `workspace`
```bash
mkdir -p .applications
git clone https://github.com/krukas/Mage2Gen .applications/mage2gen
```

After that you can run `dev mage2gen` anywhere, give it a spin
