### ISSUE TITLE
magerun2 doesn't work anymore

### ISSUE THREAD

**Issue by peterjaap** [JeroenBoersma/docker-compose-development#123]
Magerun2 has been updated and now needs at least PHP 7.2 The magerun in this environment apparently uses an older version;

```
dev magerun2 c:f
ErrorException: PHP Version is lower than 7.2.0. Please upgrade your runtime.
```

**Comment by JeroenBoersma** [comment]
ok, who uses `magerun2 ` anyway... If you have `bin/magento ca:cl` and `cache-clean.js -w -v` :-)

But we need to have different versions on different PHP images... That's new... Until now we could just load the latest Magerun...

**Comment by JeroenBoersma** [comment]
Ok, for your legacy PHP 7.1 project I'll dowgrade to 3.2.0 which is that last supported version...

**Comment by JeroenBoersma** [comment]
One last comment, this will be the last build for PHP 7.1, according to their documentation :)
https://php.net/eol.php
