### ISSUE TITLE
Increase php memory_limit for cli

### ISSUE THREAD

**Issue by jeromecx** [JeroenBoersma/docker-compose-development#124]
Hi Jeroen,

I hope everything's fine for you,
I'm working on a custom module for Magento 2 distributed via GitHub.
I've just tried to install it using composer, running this command : 
```shell
dev composer require jeromecx/module-catalog-category-banner
```

However, this command give me the following error : 

`PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 52`

Then, i tried to increase temporarily the php cli memory_limit, as explained [here](https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors) running this command : 

```shell
php -d memory_limit=-1 composer require jeromecx/module-catalog-category-banner
```
Unfortunately, this command also didn't work. I received this error message : 

`Could not open input file: composer`.

I found a solution, running : 

```shell
dev php -d memory_limit=-1 /usr/local/bin/composer require jeromecx/module-catalog-category-banner
``` 

But it was not very intuitive.

In your opinion, is there any solution to make it easier (like environment variable) ?

Thank you for your help,

Take care,

Jérôme

**Comment by JeroenBoersma** [comment]
@jeromecx firstly, thanks for bringing this up and sorry for the late reply!

I've found a more convenient way to update the memory limit from the docs in Composer
See https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors

I'll let you set it via the config file...

Will create a commit for this after this reply

**Comment by JeroenBoersma** [comment]
support COMPOSER_MEMORY_LIMIT variable in .env

open the `.env` in your favorite editor(`vim`) and add a line
```
MYSQL_ROOT_PASSWORD=password
DOMAINSUFFIX=.localhost
COMPOSER_MEMORY_LIMIT=-1
```

and it will work just fine.

**Comment by JeroenBoersma** [comment]
Also take a look on using trap as in docker land `ctrl-c` doesn't always listen to what you want..
with `dev trap composer COMMAND` you can press `ctrl-c` when you like and you'll have your terminal back in a sec.

**Comment by jeromecx** [comment]
> support COMPOSER_MEMORY_LIMIT variable in .env
> 
> open the `.env` in your favorite editor(`vim`) and add a line
> 
> ```
> MYSQL_ROOT_PASSWORD=password
> DOMAINSUFFIX=.localhost
> COMPOSER_MEMORY_LIMIT=-1
> ```
> 
> and it will work just fine.

Hello Jeroen, 

Thank you for the advice, it works like a charm !
You're right, this was the right way to do it,

Have a nice day,

Jérôme
