### ISSUE TITLE
Disable Xdebug for cli (major impact on Composer)

### ISSUE THREAD

**Issue by jeromecx** [JeroenBoersma/docker-compose-development#125]
Hi Jeroen,

Today I tried to disable the Xdebug extension for php.7.2-cli, and I did not find any solution.

Running this command only work for php7.2-fpm : 

```ssh
dev php-ext-disable xdebug
```

I would like to follow this instructions : 

https://getcomposer.org/doc/articles/troubleshooting.md#xdebug-impact-on-composer

Do you have any idea how to get there in your docker environment ?

Thanks for your help,

Take care,

Jérôme

**Comment by JeroenBoersma** [comment]
Hi Jérôme,

Thanks for bringing this up... You're right, the command online temporarily disables this for the running container(the one used for the web interface, never thought about the console...

Every command will be ran in it's own container, so it won't update the image.

As a work around:
```bash
# disable xdebug for running container
dev php-ext-disable xdbug

# login running container with  xdebug disabled
dev exec php72 su - app

# navigate to your project
cd test/project

# run composer command with disabled xdebug
composer update
```

I'll leave this open so we can fix this for the console as well

**Comment by JeroenBoersma** [comment]
@jeromecx what you prefer to disable the xdebug fully or just for a one-off command?

**Comment by peterjaap** [comment]
@JeroenBoersma wasn't this solved in a recent Xdebug release?

**Comment by JeroenBoersma** [comment]
yes latest 3.x+ releases are not affected by performance degradation anymore.
