### ISSUE TITLE
Cloned Magento needs sockets

### ISSUE THREAD

**Issue by peterjaap** [JeroenBoersma/docker-compose-development#126]
When cloning Magento from the repo (to develop on the core), it needs `php-amqplib/php-amqplib` 
(see [here](https://github.com/magento/magento2/blob/2.4-develop/composer.json#L74)) which in turn needs `ext-sockets`.

I've updated my custom Dockerfile `build/custom/php73/Dockerfile` but it would be great if this was included out of the box.

```
RUN docker-php-ext-install sockets  
RUN docker-php-ext-enable sockets
```

**Comment by JeroenBoersma** [comment]
Is it available on 7.1/7.2 ?

**Comment by peterjaap** [comment]
No

**Comment by JeroenBoersma** [comment]
Build is going!
