### ISSUE TITLE
Add Expose

### ISSUE THREAD

**Issue by peterjaap** [JeroenBoersma/docker-compose-development#129]
Expose is an open-source alternative to ngrok, so without the request limitations! https://github.com/beyondcode/expose

**Comment by JeroenBoersma** [comment]
let's do it!

**Comment by JeroenBoersma** [comment]
To expose a local project just run `dev expose`

Register yourself online, and setup the token `dev expose token TOKEN`

Because this is a php subprocess it cannot be killed with `ctrl-c` use
`ctrl-p` -> `ctrl-q` instead(docker way)
If you run it with `dev trap expose` and use `ctrl-c`

**Comment by peterjaap** [comment]
@JeroenBoersma doesn't work, here's basically the same issue; https://github.com/beyondcode/expose/issues/134
