### ISSUE TITLE
Upload containers to dockerhub

### ISSUE THREAD

**Issue by JeroenBoersma** [JeroenBoersma/docker-compose-development#13]
Instead of relying on the generated containers, upload the containers to dockerhub so they can easily be downloaded and started.
- requires me to maintain and rebuild them from time to time.

**Comment by Caroga** [comment]
It would definitely help having these containers in a public repo somewhere. 
If possible we could setup a pipeline for which checks new tagged versions so it can build and publish them? This would lower the time you'd have to invest in maintaining and rebuilding the containers.

**Comment by JeroenBoersma** [comment]
I would like to start the discussion about this.

Should we have a seperate build branch with references to images.
This would IMHO make it somewhat unclear for users if they are already on the master branch, which is basically the main branch.

Or we create a new branch `develop` which is the current state and update the master branch which links to the images.

Please provide me with some valid feedback on this.

**Comment by Caroga** [comment]
Sorry for my absence on this issue. Here is my two cents on the matter.
I believe that having just 2 types of images would be sufficient. `devel` for development/CI purposes, and tagged releases like `v1.x.x`. 
`devel` image would be build upon the `master` branch, and the tagged releases upon the tags in git.

Does this sound okay to you ?

**Comment by JeroenBoersma** [comment]
I've solved this by pushing them to the dockerhub..
I've created a develop branch where I will push to and it will trigger dockerhub automaticly.

https://hub.docker.com/r/srcoder/
