### ISSUE TITLE
docker-sync.yml file does not match the required version (2)

### ISSUE THREAD

**Issue by itsazzad** [JeroenBoersma/docker-compose-development#130]
```
       error  Your docker-sync.yml file does not match the required version (2).
```

This is what I have:
```
$ cat docker-sync.yml 
version: 3

syncs:
  web-sync:
    notify_terminal: true
    src: './workspace'
    sync_strategy: 'unison'
    sync_host_ip: '127.0.0.1'
    sync_host_port: 10871
```

**Comment by JeroenBoersma** [comment]
Hi @itsazzad, thanks for the question.

Most of us use Linux, so I ~never~ don't actively check `docker-sync.yml`  file.
Even Windows 10 has better support for file-sync nowadays.

Nevertheless I've updated the file with your feedback.
See https://github.com/JeroenBoersma/docker-compose-development/commit/10542360f5e75a267c2ae20d80a9c6894c9c643c
