### ISSUE TITLE
Container percona no create database mysql

### ISSUE THREAD

**Issue by tfmlink** [JeroenBoersma/docker-compose-development#132]
There is a problem in my installation.

I installed mysql 5.7 and mysql_secure, in a local environment with root user access to the database,
but after stopping the local mysql service and following the ./dev setp documentation all containers are installed, but when using the ./dev myroot command, it returns an access error, even configuring mysql/conf and docker-compose.yml.
The error consists in Access denied for user 'root'@'172.17.0.17' there is some point where I can change this ip address so that the mysql application works correctly

**Comment by JeroenBoersma** [comment]
Yes, the most common one is that you ran the `dev setup` the first time and a random root password was generated for this environment and the rest of the process failed...

the best you can do is keep the local mysql server stopped.. and start the setup over again with next set of commands.

```shell
# remove all running containers used
bin/dev down --remove-orphans
# remove the current "invalid" container
bin/dev volume rm dockerdev-mysql-volume

# run the setup again
bin/dev setup

```
