### ISSUE TITLE
Mac OSX configuration

### ISSUE THREAD

**Issue by gkopec** [JeroenBoersma/docker-compose-development#133]
Is here anyone who is developing M2 on OSX with default configuration? Or maybe can anyone share additional config to get M2 loading faster? I switched from Linux and must say that it's not possible to work with Docker with custom settings on Magento2.
I'm using `docker-sync` with unison. But the workspace volume is quite big, so I was wondering if I shouldn't split it for M2 volumes instead using the whole directory.
@JeroenBoersma I will close this issue if there won't be any answers.

**Comment by JeroenBoersma** [comment]
@gkopec thanks for reporting! I'm not familiar with it, so I can't dive in!
