### ISSUE TITLE
How to add new vhost containers?

### ISSUE THREAD

**Issue by pquerner** [JeroenBoersma/docker-compose-development#14]
I want to develop an app within this setup, but the app requires to be run from "public" folder. 
The app initializes there and so forth.

What file do I have to alter or to create to have this feature?

(The framework I am working with is "Lumen" by Laravel)

Thanks!

**Comment by JeroenBoersma** [comment]
For Magento 2 projects it'll lookup the public directory, `customer.project.magento2.dev` -> `workspace/customer/project/{MAGENTO2INSTALL}`

For other projects it'll lookup htdocs/httpdocs. I've added a latest commit which also allows `public` too -> `workspace/customer/project/{YOURPROJECT}` with `public` as docroot for NGINX.

**Comment by JeroenBoersma** [comment]
https://github.com/JeroenBoersma/docker-compose-development/commit/1ef3cf4682f61b3dc75fc68dae19bd9cd2367122
