### ISSUE TITLE
Inconsistent Error

### ISSUE THREAD

**Issue by cris7webjump** [JeroenBoersma/docker-compose-development#150]
hello, i've been using this docker for a long time and thanks for the nice work.

But I recently ran a dev rebuild and started getting the following error :

**2021/06/25 12:46:27 [error] 28#28: *2720 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: Warning: Unknown: Filename cannot be empty in Unknown on line 0 in /data/webjump/nav/vendor/magento/framework/App/ErrorHandler.php:61
web_1              | Stack trace:
web_1              | #0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'Unknown: Filena...', 'Unknown', 0, NULL)
web_1              | #1 {main}**

but when I refresh page, this error happens sometimes yes sometimes no. is inconsistent.

I tried to reinstall everything in a new environment and I got the same error, for every project I try to use, even in this last phpmyadmin example you posted

Has anyone here ever been through this?

![image](https://user-images.githubusercontent.com/27784325/123427587-2efe5880-d59b-11eb-9202-65f962f46c72.png)
_________________________________________________________________________________________________
![image](https://user-images.githubusercontent.com/27784325/123427541-2148d300-d59b-11eb-9344-bcd2825b2280.png)
_________________________________________________________________________________________________
just index.php
![image](https://user-images.githubusercontent.com/27784325/123442142-f797a800-d5aa-11eb-870c-850147c24d99.png)

**Comment by julienloizelet** [comment]
Hi,
Just to say that I have the same error since I ran a `dev rebuild` and `dev setup`.

Did you find some hint ?

**Comment by cris7webjump** [comment]
@julienloizelet did you find any solution?

**Comment by julienloizelet** [comment]
> @julienloizelet did you find any solution?

No, I gave up for the moment and had to use another Magento 2 docker stack ...

As you pointed in your first message, errors happen even when Magento 2 is not involved. (it can happen in phpmyadmin view). 

I had also the error when I use Mailhog : http://mail.localhost/  (no 502 but broken css)

Here are what I loggued "113: Host is unreachable" : 

```
[02/Jul/2021:05:31:41 +0000] - http://mail.localhost/ "GET / HTTP/1.0" 200 18436 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"
[02/Jul/2021:05:31:41 +0000] - http://mail.localhost/js/jquery-1.11.0.min.js "GET /js/jquery-1.11.0.min.js HTTP/1.0" 200 96381 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"
2021/07/02 05:31:44 [error] 26#26: *47 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.17.0.16, server: mail.localhost, request: "GET /js/jquery-ui-1.10.4.min.js HTTP/1.0", upstream: "http://[2001:db8:1::242:ac11:4]:8025/js/jquery-ui-1.10.4.min.js", host: "mail.localhost"
```

I tried to deactivate Varnish too : same result.

So, I guess this is not an issue with some nginx sites conf (for example build/dist/web/nginx/sites-enabled/20-magento2) but I have still no idea ...

**Comment by JeroenBoersma** [comment]
wow, let me try out today, never seen these before...

**Comment by JeroenBoersma** [comment]
most likely the php.ini isn't valid anymore for the given PHP-version, maybe a updated module... Will try to reproduce...

**Comment by JeroenBoersma** [comment]
Ok, first feedback: looks like 7.3 and up are more verbose in error reporting...
Which is in a way good.

- I've a phpmyadmin up-and-running, which doesn't complain...
- hard refreshing and chaning php versions on the fly for http://test.project.localhost/info.php works like a charm.

Next up: install a clean Magento 2.4.2-p1 with composer in workspace/m242 with PHP 7.4

Can someone share some details on which PHP version you are running? And if you downloaded Magento `zip` or used `composer` for installation?

**Comment by JeroenBoersma** [comment]
Magento 2 installation, took directory structure from @julienloizelet 

I already have my composer auth setup for Magento https://devdocs.magento.com/guides/v2.4/install-gde/prereq/connect-auth.html

## Running setup
```
cdw
mkdir m242
cd m242

# make sure we are running PHP 7.4
dev php-change php74

# create new project
dev composer2 create-project --repository-url=https://repo.magento.com/ "magento/project-community-edition:~2.4.2-p1" magento2 --prefer-dist

cd magento2
# create database
mysql -e"create database jeroen_m242_m2";
# install magento
bin/magento setup:install --backend-frontname=admin --db-host=db --db-user=jeroen --db-password='' --db-name=jeroen_m242_m2 --admin-user=jeroen --admin-password=Jeroen123 --admin-firstname=Jeroen --admin-lastname=Magento --admin-email=jeroen@m242.localhost --elasticsearch-host=elasticsearch7 --elasticsearch-index-prefix=m242

# setup urls
bin/magento conf:set -le web/unsecure/base_url https://m242.magento2.localhost/
bin/magento conf:set -le web/secure/base_url https://m242.magento2.localhost/
bin/magento conf:set -le web/secure/use_in_frontend 1

bin/magento conf:set -le general/locale/code en_US
bin/magento conf:set -le web/seo/use_rewrites 1

# put in developer mode
bin/magento dep:mode:set developer

dev logs -f web
```

Open browser and navigate to https://m242.magento2.localhost/admin/ (accept the self generated certificate)
- login
- send 2fa mail
- open https://mail.localhost/ - follow mail instructions
- setup 2fa and login

Didn't got any errors :-/

### Backend
![image](https://user-images.githubusercontent.com/1163348/124250956-aac14d80-db25-11eb-9e77-9d555156ede6.png)

### Frontend
![image](https://user-images.githubusercontent.com/1163348/124251106-d5130b00-db25-11eb-8d39-6b1f7d386690.png)

**Comment by julienloizelet** [comment]
> Ok, first feedback: looks like 7.3 and up are more verbose in error reporting...
> Which is in a way good.
> 
>     * I've a phpmyadmin up-and-running, which doesn't complain...
> 
>     * hard refreshing and chaning php versions on the fly for http://test.project.localhost/info.php works like a charm.
> 
>     * there is an error in the log about the "favicon.ico" being unavailable (which is correct for the test project, no "On line 0" yet)
> 
> 
> Next up: install a clean Magento 2.4.2-p1 with composer in workspace/m242 with PHP 7.4
> 
> Can someone share some details on which PHP version you are running? And if you downloaded Magento `zip` or used `composer` for installation?

All was working fine before I ran `dev rebuild` and `dev setup` : did you try this ?

I have multiple install (6) : from magento 2.2 to magento 2.4.2 and was used to change PHP versions depending on each Magento version requirement.

I installed it with composer.

**Comment by JeroenBoersma** [comment]
> just index.php
> ![image](https://user-images.githubusercontent.com/27784325/123442142-f797a800-d5aa-11eb-870c-850147c24d99.png)

This is interesting, the `../index.php` which could be part of the problem, how is your directory setup for PMA?

**Comment by JeroenBoersma** [comment]
And running PHPMyAdmin against PHP 8.0 breaks everything, nu sure why :-) not a primary PMA user

**Comment by julienloizelet** [comment]
> > just index.php
> > ![image](https://user-images.githubusercontent.com/27784325/123442142-f797a800-d5aa-11eb-870c-850147c24d99.png)
> 
> This is interesting, the `../index.php` which could be part of the problem, how is your directory setup for PMA?

For information, I have the same kind of message on my magento 2.4.2 home : the content is ok and error are displayed in the bottom of the page (in the better case, in the worst case, just a 502 Bad Gateway) : 
![Capture d’écran de 2021-07-02 18-27-48](https://user-images.githubusercontent.com/20956510/124254152-bd5a7780-db63-11eb-93da-4b4974588a45.png)

**Comment by JeroenBoersma** [comment]
Will deploy sample data and enable varnish

 @julienloizelet which PHP version are you running?
```
cdw
cd m242/magento2
php -v

```

**Comment by julienloizelet** [comment]
> Will deploy sample data and enable varnish
> 
> @julienloizelet which PHP version are you running?
> 
> ```
> cdw
> cd m242/magento2
> php -v
> ```
I disabled Varnish. (I'm pretty sure this is not a Magento issue as I have the same error on http://mail.localhost/ ).

But thank you for your investigation :) 

Here is the return of `dev php -v` : 
```
PHP 7.3.28 (cli) (built: Jun 23 2021 13:15:00) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.28, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.28, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans
    with blackfire v1.62.0~linux-x64-non_zts73, https://blackfire.io, by Blackfire
```

**Comment by JeroenBoersma** [comment]
> I disabled Varnish. (I'm pretty sure this is not a Magento issue as I have the same error on http://mail.localhost/ ).
But mail is not running PHP :exploding_head: :slightly_smiling_face: 

So that would mean that there is some sort of request going to a php container somewhere or cached for whatever reason

**Comment by julienloizelet** [comment]
> > I disabled Varnish. (I'm pretty sure this is not a Magento issue as I have the same error on http://mail.localhost/ ).
> > But mail is not running PHP exploding_head slightly_smiling_face
> 
> So that would mean that there is some sort of request going to a php container somewhere or cached for whatever reason

I just did the following test : 

-  run `dev logs -f web`
-  go to  http://mail.localhost/
- first line of log is 
```
web_1             | 2021/07/02 09:46:40 [error] 28#28: *524 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.17.0.16, server: mail.localhost, request: "GET / HTTP/1.0", upstream: "http://[2001:db8:1::242:ac11:4]:8025/", host: "mail.localhost"
```

**Comment by JeroenBoersma** [comment]
Thanks for this chat @julienloizelet - happy with the quick responses :)

**Comment by julienloizelet** [comment]
> Thanks for this chat @julienloizelet - happy with the quick responses :)

Thank you too for this great repo. Hope we will find a solution. Unfortunately, I have to go now; so I won't be able to continue this chat ;)

**Comment by JeroenBoersma** [comment]
> > > I disabled Varnish. (I'm pretty sure this is not a Magento issue as I have the same error on http://mail.localhost/ ).
> > > But mail is not running PHP exploding_head slightly_smiling_face
> > 
> > 
> > So that would mean that there is some sort of request going to a php container somewhere or cached for whatever reason
> 
> I just did the following test :
> 
> * run `dev logs -f web`
> * go to  http://mail.localhost/
> * first line of log is
> 
> ```
> web_1             | 2021/07/02 09:46:40 [error] 28#28: *524 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.17.0.16, server: mail.localhost, request: "GET / HTTP/1.0", upstream: "http://[2001:db8:1::242:ac11:4]:8025/", host: "mail.localhost"
> ```

This is another error, maybe IPV6... but I wouldn't relate this to the `Error on line 0` errors

**Comment by JeroenBoersma** [comment]
So I tested against PHP 7.4, now downgrading to PHP 7.3 and see what's up with that...

Maybe the problem is elsewhere, so I need a little more info:
- Which OS (WSL maybe?) `lsb_release -a`
- Which docker version `docker -v`
- Which docker-compose version `docker-compose -v`

**Comment by ligiasalzano** [comment]
Hi.
For information, I have this problem too. 
I did a fresh install on a notebook that had been formatted. I installed magento 2 (without sample data) using `composer` and PHP version 7.3. 
I'm using Ubuntu 20.04.2 LTS, docker version 20.10.7 and docker-compose 1.29.2.

At the bottom of the pages, I have this error:
`Fatal error: Uncaught Exception: Warning: Unknown: Filename cannot be empty in Unknown on line 0 in /data/study/magento2/vendor/magento/framework/App/ErrorHandler.php on line 61`
![print-frontstore](https://user-images.githubusercontent.com/20398429/124286512-6b92fc80-db25-11eb-9898-6270eb4e1f87.png)

And several times, when refreshing the page, I have this problem:
![bad](https://user-images.githubusercontent.com/20398429/124286612-86657100-db25-11eb-80f1-f79d0993af77.png)


`lsb_release -a`
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	        20.04
Codename:	focal
```

`docker -v`
```
Docker version 20.10.7, build f0df350
```

`docker-compose -v`
```
docker-compose version 1.29.2, build 5becea4c
```

`dev php -v`
```  
Creating development_php73_run ... done
PHP 7.3.28 (cli) (built: Jun 23 2021 13:15:00) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.28, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.28, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans
    with blackfire v1.62.0~linux-x64-non_zts73, https://blackfire.io, by Blackfire
```



Thanks for this repository, @JeroenBoersma! :)

**Comment by julienloizelet** [comment]
>
>     * Which OS (WSL maybe?) `lsb_release -a`
> 
>     * Which docker version `docker -v`
> 
>     * Which docker-compose version `docker-compose -v`


```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```

```
docker -v
Docker version 20.10.7, build f0df350
```

```
docker-compose -v
docker-compose version 1.24.1, build 4667896b
```

**Comment by ArjenMiedema** [comment]
@julienloizelet we found a setup on which we can reproduce the error. We will look into it from there.

**Comment by ArjenMiedema** [comment]
Did some more checks and the `docker-compose` version doesn't seem to be related to the issue. It looks more like a change that was made to the PHP images that are used. These are updated on the 23rd of June and when we do a `dev rebuild` on a system that has images prior to that date (which work as expected) we can reproduce the issue. We will look into what changes are related to the issue.

**Comment by JeroenBoersma** [comment]
This is a nice one to debug, thanks everyone...
/sarcam off

I'm finally able to reproduce the error locally sometimes :+1:

**Comment by JeroenBoersma** [comment]
Looks like PHP 7.4 and PHP 7.3 throw the error 3 times for 1 file and after that the error is gone...

PHP 8.0 is very consistent trowing the error, so will investigate further...

**Comment by JeroenBoersma** [comment]
Whoohoooo.... Found the root cause for this problem!

Something changed with the `blackfire` probe, which is shipped by default... I'll see if I can test some "older" minors to see if that solves the problem, otherwise I'll disable the module by default, so the nasty errors are gone and find out a way to submit a ticket over to blackfire :)

TBC

**Comment by JeroenBoersma** [comment]
Resume:
`blackfire.agent_socket` must have a value otherwise it throws an error, older PHP versions might ignore this after a few tries... And deprecated PHP versions are still shipped with older probes, which are not updated anymore so don't include this bug.

For years and years I had blackfire configuration enabled, this was why I couldn't reproduce it.

I will release create a fix where a default value is set for agent socket.

If you enable a working blackfire profile, the error will also be resolved.

**Comment by JeroenBoersma** [comment]
Hear hear... If you pull the latest set, please verify for me if the error is solved for this...

@ligiasalzano I've also seen the "gateway errors after several tries" could you also test if pulling the latest code and do a `dev rebuild` solves the error...

I contacted the lovely people of Blackfire and hope they can also fix this before someone is hit by this on a "production" shared environment.

**Comment by JeroenBoersma** [comment]
Everyone, thanks for collaborating on this! :heart:

**Comment by julienloizelet** [comment]
@JeroenBoersma : `git pull` and `dev rebuild && dev setup` make it work again :) 

Any reason to let this line 95 and 96 commented ? : https://github.com/JeroenBoersma/docker-compose-development/commit/5b713e9c03e03ba03a4dc96532158025b9bd6ba4#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3R96

**Comment by JeroenBoersma** [comment]
> @JeroenBoersma : `git pull` and `dev rebuild && dev setup` make it work again :)
> 
> Any reason to let this line 95 and 96 commented ? : [5b713e9#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3R96](https://github.com/JeroenBoersma/docker-compose-development/commit/5b713e9c03e03ba03a4dc96532158025b9bd6ba4#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3R96)

wow, sharp eyes... thanks! That was unintended, it was a final test before submitting... left it commented, which I pushed
