### ISSUE TITLE
Ngrok version is outdated

### ISSUE THREAD

**Issue by JCombee** [JeroenBoersma/docker-compose-development#157]
The current used ngrok container from `fnichol/ngrok` is not working anymore for the environment.
When you want to start a connecttion with ngrok through dev ngrok it gives me this:

```
Tunnel session failed: Your ngrok agent version "2.2.0" is no longer supported. Only the most recent version of the ngrok agent is supported without an account.
Update to a newer version with `ngrok update` or by downloading from https://ngrok.com/download.
Sign up for an account to avoid forced version upgrades: https://ngrok.com/signup.

ERR_NGROK_120
```

The last push to the docker hub was 5 years ago.

Now earlier this year the team of ngrok self released first party container that I think would be a good substitute https://hub.docker.com/r/ngrok/ngrok.

**Comment by JCombee** [comment]
I found that it was enought to only switch the version of ngrok.
So I made a PR for that: https://github.com/JeroenBoersma/docker-compose-development/pull/158

**Comment by peterjaap** [comment]
Thx!
