### ISSUE TITLE
Remove EOL PHP versions

### ISSUE THREAD

**Issue by ArjenMiedema** [JeroenBoersma/docker-compose-development#161]
Since it's been over a year ago that PHP 7.2 has been unsupported (and only a couple of days until the EOL for PHP 7.3), it's a good moment to say farewell to several outdated PHP versions in the Docker environment.

This means that the following PHP versions can be removed at this moment:
- PHP 5.6
- PHP 7.0
- PHP 7.1
- PHP 7.2

**Comment by esjdev** [comment]
What if working with a legacy project?

**Comment by peterjaap** [comment]
I agree with @esjdev, it shouldn't be necessary to remove these. We sometimes have legacy projects as well.

**Comment by ArjenMiedema** [comment]
If you have projects running on PHP 5.6 or PHP 7.0/7.1 your problem is a lot bigger than the fact that this Docker environment no longer supports it. These versions are end of life for more than 2 years now. So I still think that these versions can be removed. I could agree on keeping PHP 7.2 in there for now, but also that one is outdated for over a year now.

**Comment by JeroenBoersma** [comment]
so, they are commented out now, not removed! This reduces the footprint, but allows enabling if you really must
