### ISSUE TITLE
Error Windows 10 with WSL2

### ISSUE THREAD

**Issue by esjdev** [JeroenBoersma/docker-compose-development#162]
Start all containers except these **development-web-1**, **development-mongo-express-1** and **development-ssl-1**

Error in **development-web-1**

>2022/04/12 03:26:39 [emerg] 1#1: host not found in upstream "fpm:9000" in /etc/nginx/backends.conf:2
nginx: [emerg] host not found in upstream "fpm:9000" in /etc/nginx/backends.conf:2

Error in **development-mongo-express-1**

>(node:8) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Could not connect to database using connectionString: mongodb://root:example@mongo:27017/"
(node:8) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [mongo:27017] on first connect [Error: getaddrinfo EAI_AGAIN mongo
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)

Error in **development-ssl-1**

>10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/04/12 03:04:10 [emerg] 1#1: host not found in upstream "backend" in /etc/nginx/nginx.conf:47
nginx: [emerg] host not found in upstream "backend" in /etc/nginx/nginx.conf:47
2022/04/12 03:22:01 [emerg] 1#1: host not found in upstream "backend" in /etc/nginx/nginx.conf:47
nginx: [emerg] host not found in upstream "backend" in /etc/nginx/nginx.conf:47
2022/04/12 03:23:04 [emerg] 1#1: host not found in upstream "backend" in /etc/nginx/nginx.conf:47
nginx: [emerg] host not found in upstream "backend" in /etc/nginx/nginx.conf:47
2022/04/12 03:32:23 [emerg] 1#1: host not found in upstream "backend" in /etc/nginx/nginx.conf:47
nginx: [emerg] host not found in upstream "backend" in /etc/nginx/nginx.conf:47

**Did anyone manage to help?**

**Comment by JeroenBoersma** [comment]
WSL is always a bit harder to setup, there is another issue #163  on WSL created today, so maybe we could see if the solution switching to the branch https://github.com/JeroenBoersma/docker-compose-development/tree/development-docker-compose-2 helps you too

**Comment by esjdev** [comment]
> WSL is always a bit harder to setup, there is another issue #163 on WSL created today, so maybe we could see if the solution switching to the branch https://github.com/JeroenBoersma/docker-compose-development/tree/development-docker-compose-2 helps you too

Thank you very much, it worked perfectly.
