### ISSUE TITLE
Replace ElasticHQ with Elasticvue

### ISSUE THREAD

**Issue by peterjaap** [JeroenBoersma/docker-compose-development#164]
https://hub.docker.com/r/cars10/elasticvue

It is much easier to navigate through an Elasticsearch index using ElasticVue. In ElasticHQ you have to create a query each time, making it harder to search for specific documents.

**Comment by JeroenBoersma** [comment]
Ok, fixed it...

This service solely runs on your machine, and you need to connect to `http://elasticsearch:920[67]` depending on the version.

run `dev setup` to enable this service, can be run side-by-side with `elasticsearchhq`

**Comment by JeroenBoersma** [comment]
This is currently only in the `development-docker-compose-2` branch.
