### ISSUE TITLE
Error running containers

### ISSUE THREAD

**Issue by esjdev** [JeroenBoersma/docker-compose-development#165]
I'm using the development-docker-compose-2 branch

Every time I do a dev start I have to rebuild the containers because of this error that keeps getting:

`Error response from daemon: error while mounting volume '/var/lib/docker/volumes/dockerdev-workspace-volume/_data': failed to mount local volume: mount /run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu-20.04/850e472369369f9c62d883896b951c4e5ba48657c91e430225e9857574bab7f0:/var/lib/docker/volumes/dockerdev-workspace-volume/_data, flags: 0x1000: no such file or directory`

**Comment by JeroenBoersma** [comment]
Hi @esjdev missed this one... did you run `dev setup` ?

I also did a bugfix for MySQL on [June 1](https://github.com/JeroenBoersma/docker-compose-development/commit/ebbaec6f698734ade5bbbdbc06484b30dd6233b6) which resolves a bug you maybe ran into in your shell...

So, pulling the latest, running `dev setup` again should make it work

**Comment by esjdev** [comment]
> Hi @esjdev missed this one... did you run `dev setup` ?
> 
> I also did a bugfix for MySQL on [June 1](https://github.com/JeroenBoersma/docker-compose-development/commit/ebbaec6f698734ade5bbbdbc06484b30dd6233b6) which resolves a bug you maybe ran into in your shell...
> 
> So, pulling the latest, running `dev setup` again should make it work

Still having the same problem, I couldn't solve it. ;-;
