### ISSUE TITLE
Running ./bin/dev update updates ALL images

### ISSUE THREAD

**Issue by Caroga** [JeroenBoersma/docker-compose-development#18]
Hi Jeroen,

I don't know if this is ment to be, just making a ticket to check, but it seems that running `./bin/dev update` updates all of my docker images, which IMHO shouldn't happen.
Would it be possible to update this command accordingly that it only updates the images of the containers which are being used by this set ?

**Comment by JeroenBoersma** [comment]
Hi Caroga,

You're right, didn't implement that (yet ;-) )

**Comment by Caroga** [comment]
Would you want me to do it for you ?

**Comment by JeroenBoersma** [comment]
I've something prepared for this

**Comment by JeroenBoersma** [comment]
These commits resolve this issue, if there is anything else, please let me know

**Comment by Caroga** [comment]
Thanks! I will check this out later.
