### ISSUE TITLE
Allow custom shares

### ISSUE THREAD

**Issue by JeroenBoersma** [JeroenBoersma/docker-compose-development#20]
This way you can have your code wherever you want and just add it to the mapping:

-> /MyShare/Somewhere:/data/{customer}/{project}/{docroot}

**Comment by Caroga** [comment]
What would this benefit over the current situation for workspaces?

**Comment by JeroenBoersma** [comment]
Nothing, it makes it easier for people to make the shift

**Comment by JeroenBoersma** [comment]
A update on this, will not change the existing structure, will look if extra shares can be added to the vm's..
One has to link internally to the correct paths...
This way you can add extra harddisks/shares

**Comment by JeroenBoersma** [comment]
won't fix
