### ISSUE TITLE
Composer cache folder

### ISSUE THREAD

**Issue by Caroga** [JeroenBoersma/docker-compose-development#25]
I don't know if this is something that went wrong locally but lemme just ask it for the sake of sanity:

The composer container references to `/workspace/.composer` to write out his cache files etc etc. 
In my situation is was getting a lot of the following errors:
```
Cannot create cache directory /composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /composer/cache/files/, or directory is not writable. Proceeding without cache
```
Turns out that the `.composer` folder was owned by root:root and not writable for my container. 

I just changed the folder permissions for now, but I was wondering if this would be something to take a look at?

**Comment by JeroenBoersma** [comment]
That should mean you've probably ran composer as root instead of the local user, not sure howto replay this.

Just took a look at my own repo and everything went just fine..
Looks like a glitch too me, let me know if it occurs again.

**Comment by Caroga** [comment]
I'll certainly will update you next time this happens. I was convinced I don't run docker as root, but maybe I did it this time. I will check as soon as I get some time.
