### ISSUE TITLE
PHP extensions missing

### ISSUE THREAD

**Issue by peterjaap** [JeroenBoersma/docker-compose-development#28]
php7.0-xml
php7.0-curl

**Comment by JeroenBoersma** [comment]
I've a seperate [repo](https://github.com/JeroenBoersma/docker-php) for the base PHP containers...
But... libcurl is available in both PHP5/7
libxml is also enabled by default in PHP, no need to install it.

Do you miss these in the composer container maybe?

**Comment by peterjaap** [comment]
Sorry, they were there.
