### ISSUE TITLE
Add Ubuntu information how to open firewall for Xdebug

### ISSUE THREAD

**Issue by peterjaap** [JeroenBoersma/docker-compose-development#30]

**Comment by JeroenBoersma** [comment]
This is flavor specific, also people tend to choose their own firewall(ufw/iptables/shorewall/etc).
I know I've enabled this ufw firewall on your pc, otherwise it would had been turned off by default :)

Maybe we could have a section in the wiki on this.

**Comment by Caroga** [comment]
As I spoke with @JeroenBoersma earlier today, I mentioned revamping the README for this repo. I'd be happy to include said instructions in it, if you provide them for me.

**Comment by Caroga** [comment]
Any update on this matter? I found some time to do the docu rewrite this week, so if you wish to include this than copy the ubuntu specific configuration in here and I will make sure to address this in the new docu.

**Comment by JeroenBoersma** [comment]
For Ubuntu it'll be; (I'll prefer command line because I don't want to describe every graphical configuration tool)

```
sudo ufw enable # if you didn't already, shame on you
sudo ufw allow in on docker0 from 172.17.0.0/24 to 172.17.0.1/32 port 9000 comment xdebug

```

**Comment by Caroga** [comment]
Ofcourse. Also, I believe that UFW is enabled by default? I could also add the native iptables equivalent if needed?

**Comment by JeroenBoersma** [comment]
Believe again; ufw is disabled on clean installs!

**Comment by JeroenBoersma** [comment]
maybe iptables is a nice addition

**Comment by Caroga** [comment]
Okay, I just see that my first_boot script enables it, therefore the wrong believes ^^,

**Comment by JeroenBoersma** [comment]
@Caroga are you still willing to add this info?

**Comment by JeroenBoersma** [comment]
Start with `ufw` and we accept PR's on all others

**Comment by Caroga** [comment]
@JeroenBoersma yes, I will create a PR to collect all additional info and update the documentation.

**Comment by njam** [comment]
this works for me:
```
sudo ufw allow in from 172.16.0.0/12 to any port 9000 comment xdebug
```
