### ISSUE TITLE
Implement ngrok

### ISSUE THREAD

**Issue by peterjaap** [JeroenBoersma/docker-compose-development#38]
Maybe this is of any help; https://github.com/fnichol/docker-ngrok

**Comment by JeroenBoersma** [comment]
Hi @peterjaap I investigated this, because of the naming conventions we use momentarily `*.dev` with dynamic contents this won't work out-of-the-box. Because the .dev is a valid domain extension, we cannot map this publicly, also I will never enable this by default, because it will always put your safe home at risk.

After implementing #43 this would have a change to work

**Comment by JeroenBoersma** [comment]
If you don't want a third party spying on your connection you can also run a saver self-hosted solution.

Both, you and your partner ssh into the same server with port forwarding described in the ssh manual.

```
# YOU: Map your local ports to a free remote port on that machine
# - use a high port to run it as a non-root user
$ ssh -R 8080:localhost:80 -R 8443:localhost:443 [machinesomewhere] 

# PARTNER:
$ ssh -L 80:locahost:8080 -L 443:localhost:8443 [machinesomewhere]

```

This way, the local environment is shared with the remote party without breaking security by leaving something behind. If one of the two parties declines, no other connections are possible.
Yes, people need some knowlegde.

Based on this principle you could also run your own ngrok similar forwarding on the web by setting up a webserver at the remote host with a mapping and forward proxy.

**Comment by peterjaap** [comment]
Ngrok provides a domain that end users connect to; ngrok.io. .dev does not have to be (and as you said cannot be) exposed. Look at how valet share works. 

The second option you mentioned isn't feasible since ngrok is useful in a scenario where a client is the other end, thus not having the required knowledge.

**Comment by JeroenBoersma** [comment]
Your last comment is only against the `ssh` thingy which I can fully follow up, it was just a suggestion which could also work.

If I look at [wernight/ngrok](https://hub.docker.com/r/wernight/ngrok/) I see this could work with the current configuration, the problem is the forward to the existing web container.

In other words mapping `*.ngrok.io` to the `*.dev` mapping. I think it's maybe even a separate project which we can implement in the near future.

If someone has some additional details, please follow up.

**Comment by Caroga** [comment]
I don't know how far this is in being developed, but here are my 2 cents:

If you take a look at the definition of this repository/stack than you will see that it is to provide a local development environment. Keyword being local. 

Therefore, in my opinion, I do not see the necessity to provide a tunnel for others to connect and see my projects. I solved this by having a DTAP in place where the other party could access my staging area and view my work. 

I do know that this is not always the situation for everyone. So for the people who wish to do so, we could address this in the FAQ and include an example like @JeroenBoersma provided before.

**Comment by JeroenBoersma** [comment]
Pleas go and test this, isn't perfect because of hardcoded ip's

https://github.com/JeroenBoersma/docker-compose-development/tree/ngrok

**Comment by JeroenBoersma** [comment]
navigate to `workspace/test/project` invoke `dev ngrok` and the tunnel will be created
or if naming convention isn't automatic because of magento `dev ngrok hostname.project.magento.dev`

**Comment by JeroenBoersma** [comment]
![image](https://user-images.githubusercontent.com/1163348/28532292-b443ad62-7099-11e7-9613-93a79526288e.png)

![image](https://user-images.githubusercontent.com/1163348/28532303-bc5dbaa6-7099-11e7-9739-baa948501249.png)

**Comment by pquerner** [comment]
Could you say a word or two about ngrok ? I for once have executed simple (dev ngrok) in the default "test" project and I always receive 404's.

/Users/pq/development/workspace/test/project/htdocs
```
grok by @inconshreveable                                                                                          (Ctrl+C to quit)
                                                                                                                                   
Session Status                online                                                                                               
Update                        update available (version 2.2.8, Ctrl-U to update)                                                   
Version                       2.1.14                                                                                               
Region                        United States (us)                                                                                   
Web Interface                 http://127.0.0.1:4040                                                                                
Forwarding                    http://f15aed38.ngrok.io -> 172.17.0.8:80                                                            
Forwarding                    https://f15aed38.ngrok.io -> 172.17.0.8:80                                                           
                                                                                                                                   
Connections                   ttl     opn     rt1     rt5     p50     p90                                                          
                              0       0       0.00    0.00    0.00    0.00
```

```
HTTP Requests                                                                                                                      
-------------                                                                                                                      
                                                                                                                                   
GET /info.php                  404 Not Found                                                                                       
GET /favicon.ico               404 Not Found                                                                                       
GET /                          404 Not Found
```

same when I'm not in "htdocs" folder. (just workspace/test/project)

**Comment by JeroenBoersma** [comment]
We lack updates in the docs for ngrok :-)

Google recently locked the `.dev` tld and claimed it for themselves.
So, now `.localhost` is the default or from your settings ;)

You can already use `dev ngrok test.project.localhost` or if you set another value in your settings use that one... I will update the `dev ngrok` later with the correct tld.

This will work right away. We've updated the docs https://github.com/JeroenBoersma/docker-compose-development/blob/master/docs/sharing-with-the-world-via-ngrok.md too.

**Comment by JeroenBoersma** [comment]
Let me know if this will work out for you.

**Comment by peterjaap** [comment]
FYI: using the free plan for ngrok does not work for Magento 2 since M2 generates so many requests that you'll immediately hit the free usage limit.
