### ISSUE TITLE
Move Imagick installation to srcoder/development-php:php7-fpm

### ISSUE THREAD

**Issue by peterjaap** [JeroenBoersma/docker-compose-development#39]
FROM srcoder/development-php:php7-fpm
MAINTAINER Jeroen Boersma <jeroen@srcode.nl>

ARG GID=1000
ARG UID=1000

RUN groupmod -g $GID app && \
    usermod -g $GID -u $UID app

```
RUN apt-get update 
RUN apt-get install -y libmagickwand-dev imagemagick 
RUN pecl install imagick-3.4.3RC2
RUN docker-php-ext-enable imagick
```

**Comment by JeroenBoersma** [comment]
Check this out, this will make this possible, even after updating

https://github.com/JeroenBoersma/docker-compose-development/commit/16aaf7f97b2010aa36c37940f87c720e3faf18f9
