### ISSUE TITLE
PHP extension imagick is missing

### ISSUE THREAD

**Issue by peterjaap** [JeroenBoersma/docker-compose-development#41]
```
app@f91380ce7c5d:~/elgentos/magento2$ bin/magento setup:install --backend-frontname= ... etc etc
Starting Magento installation:
File permissions check...
[Progress: 1 / 461]
Required extensions check...


                                           
  [Exception]                              
  Missing following extensions: 'imagick'  
                                           
```
I'm not sure what/how to install. Imagick + Docker seems to give issues for a lot of people? `docker-php-ext-install imagick` apparently isn't enough?

**Comment by JeroenBoersma** [comment]
Adding this in your custom PHP file did the trick, if people desperately need this inside the docker containers on daily base I can reconsider adding it, for now it looks like a client specific request and the `docker-custom.yml` can provide this perfectly.

```
RUN apt-get update \
    && apt-get install -y libmagickwand-dev imagemagick \
    && pecl install imagick-3.4.3RC2 \
    && docker-php-ext-enable imagick
```

**Comment by peterjaap** [comment]
Needed for every M2 install....

**Comment by JeroenBoersma** [comment]
Consider it done, building in docker-php repo
