### ISSUE TITLE
For M2, set xdebug.max_nesting_level to -1

### ISSUE THREAD

**Issue by peterjaap** [JeroenBoersma/docker-compose-development#42]

**Comment by JeroenBoersma** [comment]
We could max it somewhat, -1 would imho be bad practice, do you have a reasonable value for this.
We will enable this globally then, the default is just the xdebug default 256.

**Comment by JeroenBoersma** [comment]
which code does break stuff, maybe a code problem, as 256 is a lot nowadays.

**Comment by peterjaap** [comment]
We ran into the limit with indexing in Magento 2. I haven't tested what the nesting level eventually was but we can begin with 1024?

**Comment by JeroenBoersma** [comment]
Resolved in PHP containers https://github.com/JeroenBoersma/docker-php/commit/b45c52421063e3786dc3a8a3d338419eaeb8aa3f
