### ISSUE TITLE
Choose your own domain (change *.dev) to whatever you want

### ISSUE THREAD

**Issue by JeroenBoersma** [JeroenBoersma/docker-compose-development#43]
Some people have their developer certificates signed and want to use their own domains.
Also, because .dev is a valid domain it can hold back people from adapting.

Implementing this would make the highest level configurable, which only affects the nginx container.
Port mappings are no concern, as default ports 80/443 can be mapped anywhere using docker.

**Comment by Caroga** [comment]
Need help on this?

**Comment by pquerner** [comment]
Like you said Google aquired the .dev TLD.
.localhost should be available.

Interesting blog post : https://iyware.com/dont-use-dev-for-development/

**Comment by JeroenBoersma** [comment]
https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/

**Comment by JeroenBoersma** [comment]
Fixing this today :+1: 
Default will be `.localhost`

You may change it to whatever you want in `docker-custom.yml`

**Comment by JeroenBoersma** [comment]
BAM, her you go, `.localhost` is the default...

I chose `.test` for myself by adding it to `docker-custom.yml` (example in `docker-compose.yml`m copy/paste)

`git pull`
`dev update && dev build && dev down && dev up`

**Comment by peterjaap** [comment]
[img]https://media.giphy.com/media/l3q2zVr6cu95nF6O4/giphy.gif[/img]
