### ISSUE TITLE
Log viewer

### ISSUE THREAD

**Issue by jamescowie** [JeroenBoersma/docker-compose-development#45]
Im thinking of adding in https://www.elastic.co/products/kibana as a combined log viewer for all services. Anyone use any different tools or happy just doing docker log ...

**Comment by JeroenBoersma** [comment]
I think this is quite interesting, momentarily everything is logged to std out.
You can use `dev logs -f` to get a combined log or use `dev logs -f {service}` to get a log for a specific service from the commandline.

I curious how system consuming this will be because of the data gathering?
Maybe you can provide some insights.

**Comment by peterjaap** [comment]
I'd love this.

**Comment by Caroga** [comment]
What is the status of this issue?

**Comment by peterjaap** [comment]
After setting this up internally at our company, I'm hestitant to incorporate this into this repository. IMHO the ELK stack is a Docker project in its own right, which you can actually find [here](https://github.com/deviantony/docker-elk).

After running that, it's as easy as setting up [Filebeat](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-getting-started.html) to pass them to Logstash and configuring Logstash to grok the logs for Magento ([like this](https://github.com/ideatosrl/logstash-magento-filter/blob/master/filter.conf)).

So I'd vote against incorporating this into this repo.

**Comment by JeroenBoersma** [comment]
For now I'll close this and keep it as a reference, feel free to re-open at any time if someone has something new on this...

I also think that adding ELK to this repo is a bit out of scope, it's possible in many ways so it has so many usecases too
