### ISSUE TITLE
Add a configuration script

### ISSUE THREAD

**Issue by JeroenBoersma** [JeroenBoersma/docker-compose-development#51]

**Comment by Caroga** [comment]
Even without description:
+1
:+1:

**Comment by Caroga** [comment]
Todo, can be updated accordingly:
- [ ] mysql password
- [ ] .dev extensie
- [ ] actieve php versions
- [ ] locatie workspace
- [ ] locatie mysql (edited)

**Comment by JeroenBoersma** [comment]
* [ ] rabittmq optional
* [ ] redis optional
* [ ] varnish optional

**Comment by JeroenBoersma** [comment]
Varnish needs a new approach, working on that, so will discard it from this ticket...

We want multiple varnish instances when running multiple projects, I'm thinking on creating a Varnish upstream via nginx..

Nginx -> Varnish(project specific) -> Nginx -> PHP

**Comment by JeroenBoersma** [comment]
Redis is on by default, is so light, we just leave it in.

**Comment by JeroenBoersma** [comment]
location of workspace is already defined in so many ways.
- on Windows it's C:\WINDOWS
- on Linux it ./workspace
- on mac it's synced, don't think this is still a issue

If you want to use it elsewhere you are already doing some advanced things, so I think you'll be just fine
