### ISSUE TITLE
"Error: [...] includes invalid characters for a local volume name [...]"

### ISSUE THREAD

**Issue by pascal08** [JeroenBoersma/docker-compose-development#53]
I'm trying to spin up this environment with this command:

```./bin/dev up```

but then the following error appears:

```
WARNING: The SSH_AUTH_SOCK variable is not set. Defaulting to a blank string.
Creating dockercomposedevelopment_php5_1
Creating dockercomposedevelopment_php71_1
Creating dockercomposedevelopment_php_1

ERROR: for php5  Cannot create container for service php5: create .: "." includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed

ERROR: for php  Cannot create container for service php: create .: "." includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed

ERROR: for php71  Cannot create container for service php71: create .: "." includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed
```

It might have something to do with the `SSH_AUTH_SOCK` variable not being set, but I'm not sure how to pass this to my docker container.

Any ideas?

**Comment by JeroenBoersma** [comment]
Hi Pascal,

Reading this looks like you don't have a ssh agent running locally..
Did you run `ssh-keygen` on your machine already, which environment are you on?

**Comment by pascal08** [comment]
@JeroenBoersma Thanks for your help! 

We managed to get it working by running `./bin/dev up` without sudo. Running it with `sudo` lead to SSH_AUTH_SOCK not being available.

**Comment by Caroga** [comment]
Just curious but what was the reason you were running the command with elevated user rights?

**Comment by JeroenBoersma** [comment]
habits from the past

"One sudo to rule them all"

**Comment by pquerner** [comment]
Somehow I have the same issue, although ```echo $SSH_AUTH_SOCK``` is not empty (in non sudo mode) and I have an ssh-agent running.

I had to remove the lines in the docker-compose.yml file from this commit https://github.com/JeroenBoersma/docker-compose-development/commit/fb7a81ad74d9c411c3675876f92b20e9ab454ee6

**Comment by JeroenBoersma** [comment]
Are you in the docker group?

`groups | grep docker`

If not, the dev command will still sudo anyway :)
