### ISSUE TITLE
Magento2 Setup Wizard not working

### ISSUE THREAD

**Issue by marciomaciel** [JeroenBoersma/docker-compose-development#54]
Hi,

O can't start magento2 wizard setup from browser. When I try to access store first time, system redirect to /setup and I have a 404 page.
My project folder structure is: workspace/opensource/magento2. URL host generated: opensource.magento2.dev

I think the /setup location specified in content/magento2 is not working propertly.

Thank you

Thank you

**Comment by JeroenBoersma** [comment]
That could, be we use the commandline for installation at all time, so this could be we never bumped in to that :)

Think I miss configured a lookup in Nginx.

For now you still can use the commandline which works perfectly

**Comment by marciomaciel** [comment]
Hi, Jeroen! Works with commandline tool. I will try fix the Nginx configuration and then make a pull request... ;) thank you

**Comment by JeroenBoersma** [comment]
Hi Marcel, looking back on this ticket, i think this will no longer be an issue? Closing this issue, happy to re-open if it is still wanted
