### ISSUE TITLE
symfony2/3 index app.php should be app_dev.php

### ISSUE THREAD

**Issue by pquerner** [JeroenBoersma/docker-compose-development#59]
Is there a reason not to use app_dev.php as index file for symfony 2/3 projects?

To fix this, make the "app_dev.php" the index file here https://github.com/JeroenBoersma/docker-compose-development/blob/master/web/nginx/content/symfony#L8
and here https://github.com/JeroenBoersma/docker-compose-development/blob/master/web/nginx/content/symfony#L19 

(instead of just app.php)

After changing this, simply restart the containers. "dev restart" or "/bin/dev restart"

**Comment by Caroga** [comment]
Imho this is nothing that needs fixing, it's a personal preference.
If you follow the symfony installation instructions then you'll notice that they supply vhost configuration pointing towards `app.php` by default. 

Therefore the default behavior is `app.tld => deployed/cached version` and `app_dev.php => development version`.

I you wish to follow your preference you can add a search/replace action by customizing the containers:
https://github.com/JeroenBoersma/docker-compose-development/blob/master/docs/customize-docker-containers.md

Hope this helps?

**Comment by pquerner** [comment]
I mean this tools purpose is entirely for development, right? Its atleast in the name of this repo.
But I guess, one could argue that its totally up to personal preference, like you said. I can understand that.

Maybe this could be added to a doc file somewhere so the info is out there and not hidden? ;)

**Comment by Caroga** [comment]
Yes, it's ment for development but not specifically Symfony development. But, that's just my view on the matter.

If you have a working setup, based on the "Customize Docker Container" section, then it could happily be added as a F.A.Q. item:)

Also, it's not that hidden ;-)
![image](https://user-images.githubusercontent.com/4005934/30021922-5943b75e-9169-11e7-8566-84436462b118.png)

**Comment by pquerner** [comment]
But the files I had to alter are not docker-compose files, or do I misunderstand you?

**Comment by JeroenBoersma** [comment]
I hereby reference @lenlorijn as he was the original author of the symfony support :-)
I'm curious about his view.

**Comment by lenlorijn** [comment]
Hey everyone!
I've actually been thinking of doing this, but there is one reason I have not.
One of the main reasons we use this docker-compose setup over local development so we can better replicate live in development.
And any feature I create I want to test in production mode, with the least amount of difference from live.
So what we could do is still use `app_dev.php` as a default, but i feel like having to add `/app.php/` to URL's I'm trying to test for a live scenario adds a difference in the URL I would like to avoid.
A neat solution would be a switcher, an environment variable for instance that determines what file will be used as a default. I'm sure PR's for a feature like this will be welcomed, right @JeroenBoersma ?

**Comment by JeroenBoersma** [comment]
Thanks for the response @lenlorijn , really appreciated.

We do exactly the same for Magento2, we redirect everything to the `pub` directory and not to the `/index.php`

I think you still can also use `/app_dev.php/` like the `/app.php/`?

**Comment by Caroga** [comment]
Thanks @lenlorijn. 

I encourage not having to adjust this, as this can be perfectly achieved by those who really wish to have everything routed to `app_dev.php` by default, by overwriting nginx's config using `docker-custom.yml`.

This is easier and would be a minor adaptation instead of forcing this on every user. Routing towards `app_dev.php` is not something you would expect as a default.

**Comment by pquerner** [comment]
Fair enough. I'm not that familiar with docker yet, so I wouldnt exactly know how to alter or create a ```docker-custom.yml``` file (even if you already mentioned it in a own documentation file).
So would you agree that this repo shouldnt force too much knowledge upon the user regarding docker related configuration, instead give "the most common" (in this case the app_dev.php "dilemma") in a seperate "example" file so the user can quickly achieve this goal ?

**Comment by Caroga** [comment]
I could create an example on how to achieve this, as this would be a valuable addition to the documentation.
But I don't want to rush things with just my opinion, so.. What do you think @JeroenBoersma ?

**Comment by pquerner** [comment]
Since this tool does give some nginx configs for Symfony, I dont see any reason not to include *useful* information to the docs.

**Comment by JeroenBoersma** [comment]
Wrong button on mobile

**Comment by JeroenBoersma** [comment]
Will change something for the web container whereby it will become easier to change such a thing yourself

**Comment by JeroenBoersma** [comment]
see #62

**Comment by pquerner** [comment]
@Caroga Did you find time yet for the example?

**Comment by Caroga** [comment]
I am terrible sorry for the current delay. Quick clarification: I've became sick and got hospitalized several times. Currently all "better" and ready to do more than I've done before.
Just to clarify, this still an issue?

**Comment by pquerner** [comment]
Wish you the best Caroga!

Imho still nice to have. More documentation means less bugging questions like this one. :D
