### ISSUE TITLE
Thumbs in Magento forbidden

### ISSUE THREAD

**Issue by peterjaap** [JeroenBoersma/docker-compose-development#60]
A url like this is now forbidden;

`http://elgentos.client.magento.dev/media/wysiwyg/.thumbs/wysiwyg/Elgentos/jennifer.gif?rand=1505217771`

Because of the `.thumbs` and this rule; https://github.com/JeroenBoersma/docker-compose-development/blob/05416ec00ae0f9aca6a4e69452710bd74f96c231/web/nginx/content/security

We need an exception for the .thumbs dir.

**Comment by JeroenBoersma** [comment]
This is bad practice for the custom module used to achieve this... With high risk in bumping into errors on production. There are too many good reasons to not include these...

I would definitely advise to change this behavior in the referring code.

But for your convenience https://github.com/JeroenBoersma/docker-compose-development/issues/59#issuecomment-329690739

**Comment by JeroenBoersma** [comment]
Will be resolved via #62
