### ISSUE TITLE
Add MySQL configuration

### ISSUE THREAD

**Issue by peterjaap** [JeroenBoersma/docker-compose-development#61]
Add these to `[mysqld]`;

```
show_compatibility_56 = ON
performance_schema = OFF
```

The first is for compatibility with MySQL 5.6 (especially the INFORMATION_SCHEMA.SESSION_VARIABLES feature). The second turns off performance schema; this is rarely necessary and I'd say users that want it enabled can enable it themselves. This allows for quicker database connections.

**Comment by JeroenBoersma** [comment]
Will merge shortly, issue is resolved.
