### ISSUE TITLE
Introduce nginx Debug Server

### ISSUE THREAD

**Issue by peterjaap** [JeroenBoersma/docker-compose-development#66]
https://www.nginx.com/blog/capturing-5xx-errors-debug-server/

**Comment by peterjaap** [comment]
Or build nginx with `--with-debug`; https://nginx.org/en/docs/debugging_log.html

**Comment by peterjaap** [comment]
I've now added `command: [nginx-debug]` to the web portion of `docker-compose.yml`

**Comment by JeroenBoersma** [comment]
fixed
