### ISSUE TITLE
Privacy Error

### ISSUE THREAD

**Issue by pascal08** [JeroenBoersma/docker-compose-development#68]
I see a [this](https://github.com/JeroenBoersma/docker-compose-development/commit/8d349d2ac81bf7fb1f4acb3900d7e18308ad0ce2) recent commit includes new self-signed certificates. I've pulled these changes, but Chrome is still complaining: `Your connection is not private`. I'm not sure if these new certs are provisioned by just restarting the containers using `dev restart`. How can I fix this?

**Comment by JeroenBoersma** [comment]
these are indeed self signed certificates...
we'll never deliver validated certificates because we just can't, your free to add you own thought.

Add them to web/nginx/certs and `dev build web && dev down && dev up`
