### ISSUE TITLE
groups: cannot find name for group ID 1049089

### ISSUE THREAD

**Issue by niners52** [JeroenBoersma/docker-compose-development#69]
On a fresh install of Docker I am trying to get this container up and running on a Windows 7 machine. I am in experienced with Docker so I am following your directions as close as possible.

When I get to this step ./bin/dev up I get an error that states-

groups: cannot find name for group ID 1049089 
export PATH=/C/Users/tyler/development/bin:${PATH}; alias cdw='cd /c/Users/tyler/development/workspace ;

Do you know what that means?

Thanks

**Comment by JeroenBoersma** [comment]
So, maybe leaving the id's the way the are in Windows would do the trick...

You can try this by commenting some code

php/Dockerfile
```
#ARG GID=1000
#ARG UID=1000

#RUN groupmod -g $GID app && \
#   usermod -g $GID -u $UID app
```

bin/dev_command/console
```
#dc opt "-u $(id -u):$(id -g)"
````

Let me know if it helps

**Comment by niners52** [comment]
Thank you for the reply, I will give it a shot.

**Comment by JeroenBoersma** [comment]
closing this issue because I think the comment fixed the issue, if this is not the case, please @niners52 let met know
