### ISSUE TITLE
Symlinks in workspace

### ISSUE THREAD

**Issue by pquerner** [JeroenBoersma/docker-compose-development#70]
I have a project which is outside of the normal workspace folder.
"docker-sync" doesnt seem to support that, - or the config for that is missing (that it can support symlink).

Can you take a look, please? Even a simple ```ln -s``` on the test project folder doesnt work.

**Comment by JeroenBoersma** [comment]
This would also fail in Linux, it's bound to the mount point, everything outside workspace isn't mounted inside the running containers.

Is it possible to turn it around?

Move the project to the workspace and symlink it on the physical machine?
Than the files will become available in your containers. ATM only a dead symlink is available in the containers.

**Comment by pquerner** [comment]
Are you on Linux and can test it?

Now I have moved the project files inside the "workspace" folder and symlink it away from there. So this way it works, but its kinda meh. Because project files are not only sourcecode files.

**Comment by JeroenBoersma** [comment]
You can also move only the source files inside the workspace and symlink a deeper level from outside, which will accomplish the same.

**Comment by pquerner** [comment]
Yep, that would work. 
Then again, I dont see why symlinking would fail. 
Does it fail on your Linux maschine as well? So we know either

a) its a mac issue
b) its a docker issue
c) its a issue from your scripts perhaps

**Comment by JeroenBoersma** [comment]
YES, this wil is because how Docker is build... This is the same for Linux/Windows/Mac.

I only share some directories with the containers, not all.

**Comment by JeroenBoersma** [comment]
So, it's not a issue, but b) would come closest as an answer.

**Comment by pquerner** [comment]
OK, gotcha. Then this can be closed I think.

**Comment by JeroenBoersma** [comment]
ok, thanks!
