### ISSUE TITLE
Unable to create files

### ISSUE THREAD

**Issue by pquerner** [JeroenBoersma/docker-compose-development#73]
I'm trying to create a simple file, using fwrite - and it fails. I think its because "root" is the owner of my files (using docker-sync if that matters). 
Same issue with Sqlite for instance (create a small database).
(I used this gist for sqlite https://gist.github.com/bladeSk/6294d3266370868601a7d2e50285dbf5#file-sqlite-php-quickstart-php-L96)

```
I have no name!@91357039bb7f:/data$ ls -lah
total 20K
drwxr-xr-x 5 root root 4.0K Jan 25 08:37 .
drwxr-xr-x 1 root root 4.0K Jan 30 15:08 ..
drwxr-xr-x 2 root root 4.0K Jan 25 08:37 .composer
drwxr-xr-x 3 root root 4.0K Jan 25 08:37 test
```
(this is from dev console)

I'm on Mac Sierra 10.13.2 (17C205).

```
Docker for Mac: version: 17.12.0-ce-mac49 (d1778b704353fa5b79142a2055a2c11c8b48a653)
macOS: version 10.13.2 (build: 17C205)
logs: /tmp/810C3696-65C8-48E5-9197-C7623AE05DA4/20180130-160913.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

```

docker-info

```
Containers: 8
 Running: 8
 Paused: 0
 Stopped: 0
Images: 32
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: CZJI:HOYG:UAQQ:GC7O:ZCDD:ETBG:WOZT:2ZNB:HNMO:RJM5:LDXS:4GZI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 66
 Goroutines: 72
 System Time: 2018-01-30T16:04:13.177671276Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by JeroenBoersma** [comment]
I'll have to excuse myself for not knowing the answer to this question. I'm not a Mac user.

From what I can tell, on Mac the user id is not found..

Maybe you can try to alter the `bin/dev_command/console` and comment the `dc opt -u ` line

**Comment by pquerner** [comment]
What command are you referring to? So I can test if that command works on Mac aswell.
Should be the same, since its based off Linux in some wierd way. And most "standard" tools are available here.

**Comment by peterjaap** [comment]
"Should" being the key word in "should be the same". Mac is not based off Linux, Mac is based off Unix, which Linux is also based off. But they are wildly varying platforms and pretty much nothing is exactly the same.

**Comment by pquerner** [comment]
Mac-06:~ pq$ id -u
503
Mac-06:~ pq$ id -g
20

**Comment by pquerner** [comment]
https://github.com/JeroenBoersma/docker-compose-development/blob/master/docker-compose-osx.yml#L15
@JeroenBoersma That might be the issue here.. ;)
Any idea why its ro (read only), when it should be rw (readwrite) ?

**Comment by JeroenBoersma** [comment]
@pquerner web is always RO(line number is updated because we've implemented php72), web is Nginx and is a dumb file serving web server.
https://github.com/JeroenBoersma/docker-compose-development/blob/master/docker-compose-osx.yml#L18

**Comment by JeroenBoersma** [comment]
closing this issue for now, think all questions are answered for now.
If you have anything, hit me up and I'll re-open this ticket
