### ISSUE TITLE
Bind to mysql/ fails if the directory is non existent

### ISSUE THREAD

**Issue by pquerner** [JeroenBoersma/docker-compose-development#80]
If the local directory `mysql` is non existent, `bin/dev up` fails with

```
Creating development_mailcatch_1 ... 
Creating development_db_1        ... error
Creating development_redis_1     ... 
Creating development_mailcatch_1 ... done
ERROR: for development_db_1  Cannot create container for service db: b"error while mounting volume with options: type='none' device='/Users/pq/projects/development/mysql' o='bind': no such file or directoryCreating development_redis_1     ... done

ERROR: for db  Cannot create container for service db: b"error while mounting volume with options: type='none' device='/Users/pq/projects/development/mysql' o='bind': no such file or directory"
ERROR: Encountered errors while bringing up the project.
```

It can be corrected with `mkdir mysql`.

Imho it should be noted in the readme and/or the line 

```
docker volume create -o 'type=none' -o 'device='${PWD}'/mysql' -o 'o=bind' dockerdev-mysql-volume
```

must be fixed by created the directory for you, if it doesnt already exists of course.

**Comment by JeroenBoersma** [comment]
@pquerner Nice find, didn't ran into this because I always had this directory, I was in the understanding that docker did this automatically.

Would you mind creating a PR?

**Comment by JeroenBoersma** [comment]
Updated readme, thanks again

**Comment by pquerner** [comment]
Its something the setup script could easily do for you. :) If I have some more time on my hands I'll try to be more productive here.
