### ISSUE TITLE
Add Elasticsearch & RabbitMQ

### ISSUE THREAD

**Issue by peterjaap** [JeroenBoersma/docker-compose-development#88]
Magento 2.3 uses Elasticsearch by default. RabbitMQ is not necessary per se, as you can use the MySQL message queue Magento also provides, but it would be definitely nice.

**Comment by JeroenBoersma** [comment]
merged with master...

`dev setup` will ask you if you want to  enable one or both of these..

You can also `touch conf/rabbitmq` or `touch conf/elasticsearch` to enable them.
`dev down && dev up` to reflect the changes
