### ISSUE TITLE
Add npm, gulp, create-react-app etc.

### ISSUE THREAD

**Issue by rickkuilman** [JeroenBoersma/docker-compose-development#90]
Since Magento needs `npm` for installing/building its javascript modules and other npm related compilers, it might come in handy to supply a container for it.

We might need to discuss what packages are essential

**Comment by JeroenBoersma** [comment]
It'll be in upcoming release https://github.com/JeroenBoersma/docker-compose-development/pull/95

**Comment by JeroenBoersma** [comment]
Please let me know which `dev npm|node|yarn` mappings I could add, or join on the running PR

**Comment by JeroenBoersma** [comment]
Released in master...

`dev node npm` and `dev node yarn` are working
