### ISSUE TITLE
Update magerun2 for Magento 2.3 compat

### ISSUE THREAD

**Issue by peterjaap** [JeroenBoersma/docker-compose-development#91]
https://magerun.net/n98-magerun2-v3-0-4-released/

**Comment by JeroenBoersma** [comment]
Please update your PHP images
`for a in srcoder/development-php:php71-fpm srcoder/development-php:php7-fpm srcoder/development-php:php73-fpm srcoder/development-php:php5-fpm srcoder/development-php:php72-fpm; do docker pull $a; done`
`dev rebuild`
