### ISSUE TITLE
Add mage2tv/magento-cache-clean

### ISSUE THREAD

**Issue by peterjaap** [JeroenBoersma/docker-compose-development#92]
Now Vinai has made mage2tv/mage-cache-clean working with Docker (see https://github.com/mage2tv/magento-cache-clean/issues/31), we can incorporate this into our dev environment so it's globally available!

**Comment by JeroenBoersma** [comment]
I've tested this on https://github.com/JeroenBoersma/docker-compose-development/pull/95
So, please checkout this `branch` to get node up-and-running

I'll suggest we do this the same as for all the scripts we use.

```bash

# Install globally
dev php composer global require mage2tv/magento-cache-clean
## Navigate to your Magento2 base-dir
# In your project create the var/cache-clean-config.json
dev php /data/.composer/vendor/mage2tv/magento-cache-clean/bin/generate-cache-clean-config.php
# Run to start watching
dev node .composer/vendor/mage2tv/magento-cache-clean/bin/cache-clean.js --watch
````

After this add this to your `.aliases` file:

```bash
cache-clean.js () {
	dev php /data/.composer/vendor/mage2tv/magento-cache-clean/bin/generate-cache-clean-config.php
	dev node /data/.composer/vendor/mage2tv/magento-cache-clean/bin/cache-clean.js "$@"
}
```

**Comment by JeroenBoersma** [comment]
If this works I need to finalize some minor things for node, and will merge with upstream.

**Comment by JeroenBoersma** [comment]
I've merged node support with master... 

We should update the docs thought

**Comment by govereem** [comment]
Small update:
`
# Install globally
dev composer global require mage2tv/magento-cache-clean
## Navigate to your Magento2 base-dir
# In your project create the var/cache-clean-config.json
dev php /data/.composer/vendor/mage2tv/magento-cache-clean/bin/generate-cache-clean-config.php
# Run to start watching
dev node  /data/.composer/vendor/mage2tv/magento-cache-clean/bin/cache-clean.js --watch
`

**Comment by peterjaap** [comment]
Nice! :tada:

**Comment by WouterSteen** [comment]
:heart:
