### ISSUE TITLE
Error tijdens opzetten magento2 

### ISSUE THREAD

**Issue by grebbekevin** [JeroenBoersma/docker-compose-development#93]
Beste Jeroen,

Ik heb jou docker omgeving opgezet. Echter krijg ik nu de volgende error:
UnexpectedValueException: The stream or file "/data/test/project/magento2//var/log/system.log" could not be opened: failed to open stream: Permission denied in /data/test/project/magento2/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107 Stack trace: #0 /data/test/project/magento2/vendor/magento/framework/Logger/Handler/Base.php(88): Monolog\Handler\StreamHandler->write(Array) #1 /data/test/project/magento2/vendor/magento/framework/Logger/Handler/System.php(62): Magento\Framework\Logger\Handler\Base->write(Array) #2 /data/test/project/magento2/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Magento\Framework\Logger\Handler\System->write(Array) #3 /data/test/project/magento2/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\Handler\AbstractProcessingHandler->handle(Array) #4 /data/test/project/magento2/vendor/magento/framework/Logger/Monolog.php(48): Monolog\Logger->addRecord(400, 'SQLSTATE[HY000]...', Array) #5 /data/test/project/magento2/vendor/monolog/monolog/src/Monolog/Logger.php(707): Magento\Framework\Logger\Monolog->addRecord(400, 'SQLSTATE[HY000]...', Array) #6 /data/test/project/magento2/vendor/magento/framework/App/Bootstrap.php(263): Monolog\Logger->error('SQLSTATE[HY000]...') #7 /data/test/project/magento2/pub/index.php(40): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor)) #8 {main}

Ik vraag me vooral af (aangezien de documentatie nog een beetje vaag is) hoe het werkt met de htdocs etc wanneer je met magento2 werkt.
Ik heb nu namelijk: workspace/test/project/<Mijn magento installatie>
En ik heb geprobeerd: workspace/test/project/magento2/pub -> symlink naar workspace/test/project/htdocs

Kun jij mij wat meer vertellen over hoet het precies werkt?

**Comment by JeroenBoersma** [comment]
> aangezien de documentatie nog een beetje vaag is
> en: because the docs are a little vage
sorry on that... And you are correct, should need some re-work :-)
Most of the time, new features land before documentation.

Besides, happy to explain it here and help you out.

Your question is on path mappings within the setup and why momentarily it results in a access writing error.

I do some assumptions here: You run a Linux flavor with docker, you run docker and your current user is in the `docker` group, you use the default extension `.localhost` for url's

The basics are in here https://github.com/JeroenBoersma/docker-compose-development#3-now-setup-your-projects

**On Magento2** Just make sure that the url you are using ends `.magento2.localhost`, so `https://test.project.magento2.localhost/` This will load all correct Magento 2 configuration in Nginx.

You can install Magento 2 in `workspace/test/project`, this will leave you with `workspace/test/project/pub/index.php`  No symlinking is needed if you do it this way.

If you don't wan't `.project.magento2`, you can also install your Magento 2 in `workspace/test/magento2`, then the url will be `https://test.magento2.localhost/`

If you still get the same error, double check if you are in the `docker` group(`groups`), if not `sudo usermod -aG docker YOURUSERNAME` logout/login, `dev rebuild` and let me know

**Comment by JeroenBoersma** [comment]
closing this as I think it is resolved, please re-open if you have some additional questions.
