### ISSUE TITLE
Cannot install Magento 2 cron jobs

### ISSUE THREAD

**Issue by RenanLazarotto** [JeroenBoersma/docker-compose-development#96]
Hiya! Me again.

I'm having a bad time while trying to install Magento 2 cron jobs. When running bin/magento cron:install, the output is:
```
renan@feren:~/docker/workspace/project/magento2$ mg cron:install
Error during saving of crontab: sh: 7: crontab: not found
```

At first, I tought it was something related to my machine's cron being stuck (or not installed for whatever reason), but when I ran `crontab -l`, this was the output:
```
renan@feren:~/docker/workspace/project/magento2$ crontab -l
no crontab for renan
```
I've then created a crontab running `crontab -e`:
```
renan@feren:~/docker/workspace/project/magento2$ crontab -e
no crontab for renan - using an empty one
```
Re-run the `bin/magento cron:install`, same as before:
```
renan@feren:~/docker/workspace/project/magento2$ mg cron:install
Error during saving of crontab: sh: 7: crontab: not found

(mg is an alias for bin/magento that I've created for the sake of simplicity)
```
However, running `bin/magento crun:run` yelds no errors:
```
renan@feren:~/docker/workspace/project/magento2$ mg cron:run
Ran jobs by schedule.
```
Talking to my coworkers, we ended up agreeing that `cron:install` tries to install the cron jobs inside the container. We cannot use the `dev/tools/cron.sh` file [because it no longer exists](https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-cron.html) (for Magento 2 > 2.2). A simple solution (or workaround) would be add the `cron:run` task to crontab, but this feels a little hackish for me.

So, there is something that can be done? My docker knowledge is quite limited, so I don't know if it is possible to bypass this and tell the container to use the host crontab instead of trying to add it inside the container.

**Comment by RenanLazarotto** [comment]
Well, I guess I managed this on my own, so I'll write this for anyone that happens to face the same isse (if any).

When I ran `cron:install`, I forgot one thing: the PHP is running inside a container, too, so Magento will try to install its cron jobs inside the container's `crontab` file. Since the file doesn't exist, it fails. However, as I noticed later, running `cron:run` yelds no errors at all and works as intented. Solution: add a task that calls `cron:run` on my `crontab`!

The problem: PHP is running inside a container, and since the `bin/magento` is a php file, I have to make sure that PHP is running. Then, there is the fact that the cron user doesn't knows my aliases, and therefore I cannot just make a task that calls `bin/magento` directly because it will not find the `php` command from inside the container.

Thankfully, the solution was quite simple: call the command from the `dev console`. [It is even on the docs here](https://github.com/JeroenBoersma/docker-compose-development/blob/master/docs/mysql-mailhog-redis-cronjobs.md), but quite unexplained, IMO.

So, the solution:
```
#!/bin/bash

date=$(date '+%d-%m-%Y %H:%M:%S' | tr -d '\n')
mgcron=$(/path/to/development/stack/bin/dev console /data/project/magento2/bin/magento cron:run)

echo -e '[\e[36m'$date'\e[0m] - Starting \e[1;94mbin/magento cron:run\e[0m...'
echo -e '[\e[36m'$date'\e[0m] - '$mgcron
```

Copy this into some file, edit your paths, make it executable (`chmod +x filename`) and add it to your crontab:

`* * * * * /path/to/your/script`

If you want to log the script output, just redirect it to a file:

`* * * * * /path/to/your/script >> /path/to/your/log/file`

This is how I solved this problem. I hope it helps!

**Comment by JeroenBoersma** [comment]
@RenanLazarotto thanks for adding the feedback and you're correct, no crontab inside the container, you can perfectly kick them via your own Crontab

The `bin/magento` actually a php script, so you could also run it with `dev php bin/magento` or `php` if you've added the `PATH`

There are also good reasons not automatically running crons on development environments.

**Comment by RenanLazarotto** [comment]
> The `bin/magento` actually a php script, so you could also run it with `dev php bin/magento` or `php` if you've added the `PATH`

I'm quite sure that Linux handles `PATH`pretty much like Windows does: you have one, system-wide `PATH` variable and one, user-wide. Since I've added the path to the `dev` inside my `.bash_rc` file, it doesn't get recognized system-wide, because of this the crontab user can't find it. Thats why I've created the script, its easier to maintain. Please correct me if I'm wrong about the whole `PATH` thing (I'm still quite new to Linux-way of doing/handling things).

> There are also good reasons not automatically running crons on development environments.

I can imagine a few reasons, but can you explain why, from your perspective? It feels like this is something I should know in order to avoid unforeseen consequences :)

**Comment by JeroenBoersma** [comment]
> I'm quite sure that Linux handles PATHpretty much like Windows does: you have one, system-wide PATH variable and one, user-wide. Since I've added the path to the dev inside my .bash_rc file, it doesn't get recognized system-wide, because of this the crontab user can't find it. Thats why I've created the script, its easier to maintain. Please correct me if I'm wrong about the whole PATH thing (I'm still quite new to Linux-way of doing/handling things).

You can add `PATH` in top of your `crontab`, but I also think adding a script for this makes it easier to maintain...

If you want a solutions for multiple projects, when a script is moved into `workspace/bin` and has execute rights, these can be ran with `dev yourowncommand` and will be ran in the correct php version.

For instance move your script to `workspace/bin/magecron`
```bash
#!/bin/bash

cd $1;

date=$(date '+%d-%m-%Y %H:%M:%S' | tr -d '\n')

echo -e '[\e[36m'$date'\e[0m] - Starting \e[1;94mbin/magento cron:run\e[0m...'
echo -e '[\e[36m'$date'\e[0m] - '$(bin/magento cron:run)
```

After this you can add in your cron:
```
* * * * * /path/to/development/bin/dev magecron project/magento2
* * * * * /path/to/development/bin/dev magecron otherproject/magento2
```

> I can imagine a few reasons, but can you explain why, from your perspective? It feels like this is something I should know in order to avoid unforeseen consequences :)

Most importantly; people still tend to copy production data to local machines and thereby copying email configurations with it, this way people would unintentionally send emails to real customer fromdeveloper machines and potentially degrading mail reputation of the customer. This would be invisible at first because it was ran via the cronjobs.

Removing mail settings of coarse will send all emails to 'https://mail.localhost/', but sometimes you just want to be in control of this.

You can invoke individual jobs via `magerun2 sys:cron:run` and this way you have more control over what you are doing. Magerun2 is shipped by default. `magerun2 sys:cron:list` will show all available cronjobs within Magento 2.
