### ISSUE TITLE
Installing on MacOS fails to build

### ISSUE THREAD

**Issue by troydynojet** [JeroenBoersma/docker-compose-development#97]
On MacOS Mojave, my install would fail, and would just generate a bunch of dots over and over again. The only hint in the output was: tr: Illegal byte sequence 

I was able to trace this through and found the issue was related to the auto-generated password via urandom. 
The fix was in bin/dev_command/setup line 11 
to include the locale declaration before tr.

`export MYSQL_ROOT_PASSWORD="`< /dev/urandom LC_CTYPE=C tr -dc _A-Z-a-z-0-9 | head -c${1:-32};echo;`";`

**Comment by JeroenBoersma** [comment]
Ah, thanks for this feedback, I guess the command `tr` divers from the Unix version... without the `LC_CTYPE`

I've looked to a most default way of doing this, but now we bump into differences.

Updated in master
