### ISSUE TITLE
Magento's setup:install command is not working

### ISSUE THREAD

**Issue by camslice** [JeroenBoersma/docker-compose-development#99]
Seems to be an issue with the DB configuration. I've already gone through these setups:

Access DB as root:
```
./bin/dev myroot
```

Create 'magento' database:
```
CREATE DATABASE magento;
```

Create magento@db user with full privileges:
```
CREATE USER 'magento'@'db' IDENTIFIED BY 'magento';
GRANT ALL PRIVILEGES ON * . * TO 'magento'@'db';
FLUSH PRIVILEGES;
```

Then using this command from the Magento docs (https://devdocs.magento.com/guides/v2.3/install-gde/composer.html)

```
bin/magento setup:install \
--base-url=http://test.project.localhost \
--db-host=db \
--db-name=magento \
--db-user=magento \
--db-password=magento \
--backend-frontname=admin \
--admin-firstname=admin \
--admin-lastname=admin \
--admin-email=cam@madebycam.com \
--admin-user=admin \
--admin-password=admin123 \
--language=en_US \
--currency=IDR \
--timezone=Asia/Jakarta \
--use-rewrites=1
```

I get the following error:
```
SQLSTATE[HY000] [2002] No such file or directory

In InstallCommand.php line 264:

  Parameter validation failed
```

I'm on macOS 10.14.5

Is there something obvious I'm doing wrong?

Thanks

**Comment by camslice** [comment]
Ok I think the problem was:
```GRANT ALL PRIVILEGES ON * . * TO 'magento'@'db';```
Should be:
```GRANT ALL PRIVILEGES ON 'magento' . * TO 'magento'@'db';```
Will double check and confirm

**Comment by camslice** [comment]
Also, should note that it obviously works with just using the root user and password from `.env`

**Comment by JeroenBoersma** [comment]
@camslice thanks for reaching out...

I would say, the feedback from `bin/magento` lacks a bit...

normally `*.*` should give enough privileges to do the above...
I'll test it for you because I've a slightly other user setup locally with users in MySQL.

**Comment by JeroenBoersma** [comment]
Ok, I don't have a Mac, but I don't think it should end in a problem...

```
dev myroot
grant all on magento.* to 'magento'@'%' identified by 'magento';
```
While I typed I saw the actual problem...
Because of docker we need to allow all hosts(`%`), in yours only allowed host is `db`, use '%' instead and it will work like a charm.

**Comment by JeroenBoersma** [comment]
just tested it locally and it worked like a charm, I think I'll make a asciinema for this

**Comment by JeroenBoersma** [comment]
Here you go!
https://asciinema.org/a/254081
